### ISSUE TITLE
revwalk: Support asking if a commit is hidden (checking "uninteresting" flag)

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3867] opened 2016-07-21 09:33 UTC
For some algorithms, it would help to ask the revwalk if a commit is hidden, which the revwalk can easily do by checking the "uninteresting" flag.  Could libgit2 provide a function `git_revwalk_commit_is_hidden` that takes a commit ID and returns a boolean indicating if the commit is hidden?

**Comment by carlosmn** [comment] 2016-07-24 16:06
I don't believe we can. For many walks, we don't know by design whether it's hidden or not. We only walk down the graph as much as we need in order to be sure that we're returning the correct set of objects. Anything past those won't be marked.

**Comment by ethomson** [comment] 2018-10-21 02:13
I agree with @carlosmm, and this is quite old, so I’m closing it.  Happy to see a PR if you have a solution that fits your needs, though.

**Closed by ethomson** 2018-10-21 02:13 UTC
