### ISSUE TITLE
No configuration exists for system level for  "C:\Program Files\Git\mingw64\etc"

### ISSUE THREAD

**Issue by ravivasani75** [libgit2/libgit2#5816] opened 2021-03-03 11:32 UTC
### Reproduction steps
Used libgit2 with vcpkg 
### Expected behavior
Should open system level config
### Actual behavior
No configuration exists for system level
I think it is mostly happening when system config is placed at C:\Program Files\Git\mingw64\etc
When path is C:\Program Files\Git\etc, config access is successful
### Version of libgit2 (release number or SHA1)
1.1.0
### Operating system(s) tested
Windows 10

**Comment by ethomson** [comment] 2021-03-03 11:58
> Should open system level config

This is not really a thing that exists on Windows.  There's no such thing as the _system level config_.  Git's "system" configuration is really a "Git for Windows" installation specific configuration.

That is to say that if you install Git for Windows at `C:\Foo` and again at `C:\Bar`, each of those installations will have unique "system configuration"s.

libgit2 has no idea what's going on with your different installations.  All we can do is take a best-effort approach to find it and figure this out.  There was an attempt to resolve this problem which - regrettably - involved adding a _fourth_ configuration file area to Git for Windows and then - even more regrettably - was hasily removed.

If you have a suggestion for what to do, I'm all ears, but otherwise, I regret that this is "by design', even if the design is wretched.

**Comment by ravivasani75** [comment] 2021-03-03 12:53
Thanks @ethomson 
As you mentioned each installation will have unique system configuration, I tried multiple installation of git and figured out that libgit2 uses git itself internally (by looking at systems envs, I think). 
But still thing remains same. It can only detect config file placed at Git\etc\ and not Git\mingw64\etc\
Currently, on many Windows systems, config path selected during installation of git is Git\mingw64\etc\
So, that will fail.

If I'm right that libgit2 internally uses git for looking for config files, then it should be able to find right config.
We can include normal paths for system config for finding it. Like Git\etc\,  Git\mingw64\etc\, ProgramData\Git\config etc.

**Comment by ravivasani75** [comment] 2021-03-03 13:00
Thanks @ethomson
As you mentioned each installation will have unique system configuration, I tried multiple installation of git and figured out that libgit2 uses git itself internally (by looking at systems envs, I think).
But still thing remains same. It can only detect config file placed at Git\etc\ and not Git\mingw64\etc
Currently, on many Windows systems, config path selected during installation of git is Git\mingw64\etc
So, that will fail.

If I'm right that libgit2 internally uses git for looking for config files, then it should be able to find right config.
Another thing that is coming to me is that we can include normal paths for system config for finding it. Like Git\etc, Git\mingw64\etc, ProgramData\Git\config etc.

**Comment by ethomson** [comment] 2021-03-03 15:27
> If I'm right that libgit2 internally uses git for looking for config files, then it should be able to find right config.

No, we definitely do not.  libgit2 is a complete reimplementation.

We look at environment variables to try to figure out where git *is* but that's so that we can resolve its configuration.

**Comment by ravivasani75** [comment] 2021-03-04 06:03
OK. I understood the process.
Please handle just path "C:\Program Files\Git\mingw64\etc" if possible, because git installation on some Windows system is using that path for gitconfig.
Thank you.

**Comment by csware** [comment] 2021-03-17 09:07
Is this related to #5773?

**Comment by ethomson** [comment] 2021-03-20 10:11
Aha, yes, indeed it looks like it is.  I'd love to see #5773 updated so that it's not using `wcscat` and friends, and using `git_buf` to construct strings more safely and then turning them into UCS-2 to call the Windows APIs.

**Comment by csware** [comment] 2021-03-20 15:51
@ethomson You took #5773 from my original PR, so it's up to you now.

**Comment by ethomson** [comment] 2021-03-20 17:10
i reopened it because it was automatically closed when we changed default branch names.

**Comment by csware** [comment] 2021-03-21 11:58
I'm not able to handle it at the moment. Also, we deal with wchar_t instead of just char, therefore, using git_buf is not that easy.

**Comment by ethomson** [comment] 2021-03-21 16:22
No worries @csware - I just meant that I don't have time either right now.  😓

**Comment by ethomson** [comment] 2022-02-13 20:18
Fixed via #5773

**Closed by ethomson** 2022-02-13 20:18 UTC
