### ISSUE TITLE
Atom is crashing due to a libgit2 bug

### ISSUE THREAD

**Issue by niltz** [libgit2/libgit2#3553] opened 2015-12-21 15:57 UTC
I recently opened an issue on the Atom repo because the editor keeps crashing. However, they think it might be an issue with libgit2.

See https://github.com/atom/atom/issues/9880 for more details and a crash dump of Atom.

If you would like more details let me know.

**Comment by carlosmn** [comment] 2015-12-29 13:27
This is a dupe of #2586 but so far nobody has been able to produce a repo/file they can share which would reproduce it.

**Closed by carlosmn** 2015-12-29 13:27 UTC
