### ISSUE TITLE
Pushing "refs/tags/*:refs/tags/*" refspec does not work

### ISSUE THREAD

**Issue by silenio** [libgit2/libgit2#3640] opened 2016-02-26 00:36 UTC
I am trying to implement "git push --tags". Is the refspec "refs/tags/*:refs/tags/*" supposed to work?

**Comment by silenio** [comment] 2016-02-26 00:37
I always get this error "Not a valid reference 'refs/tags/*'".

**Comment by ethomson** [comment] 2016-02-29 03:38
This appears to be a duplicate of #1125

**Comment by carlosmn** [comment] 2016-02-29 09:35
Yes, this is a known limitation and so far nobody has stepped up to have push accept refspecs with patterns. You will have to pass in the list of tags you wish to push. Closing as duplicate.

**Closed by carlosmn** 2016-02-29 09:35 UTC
