### ISSUE TITLE
Files are not excluded as expected

### ISSUE THREAD

**Issue by williamdes** [libgit2/libgit2#4902] opened 2018-12-02 12:56 UTC
### Node git
- Unzip [testbench.zip](https://github.com/libgit2/libgit2/files/2636925/testbench.zip)
- npm install
- `node status.js`
- Files are marked as new
- `cd test-repo/`
- `git status`
- No new files

### Manual
- git clone https://github.com/phpmyadmin/phpmyadmin
- cd phpmyadmin
- git reset --hard 61b98cf9cc821f9a500a4fe374da92a59b965092
- npm run css-compile
- You can see using GitKraken (they use libgit2) that the files are marked as new
- Same using the following code
```js
var nodegit = require("nodegit"), path = require("path");
nodegit.Repository.open(path.resolve(__dirname, "test-repo/.git"))
  .then(function(repo) {
    repo.getStatus().then(function(statuses) {
      function statusToText(status) {
        var words = [];
        if (status.isNew()) { words.push("NEW"); }
        if (status.isModified()) { words.push("MODIFIED"); }
        if (status.isTypechange()) { words.push("TYPECHANGE"); }
        if (status.isRenamed()) { words.push("RENAMED"); }
        if (status.isIgnored()) { words.push("IGNORED"); }

        return words.join(" ");
      }

      statuses.forEach(function(file) {
        console.log(file.path() + " " + statusToText(file));
      });
    });
});
```

### Expected behavior
Like when using git, files are ignored

### Actual behavior
Files as flagged as new and not ignored

### Version of libgit2 (release number or SHA1)
Using https://github.com/nodegit/nodegit (0.23.0)
libgit2@v0.27.3

### Operating system(s) tested
Linux (Ubuntu 18.04)

**Comment by pks-t** [comment] 2018-12-19 10:19
Thanks for your report!

Since the release of v0.27, there were two fixes with regards to gitignore rules. First was for gitignore entries that have trailing whitespaces, but phpmyadmin does not have any of those. Second was when unignoring a directory ("!/foo/"), then we were erroneously unignoring all of its contents, too. I suspect that this may be the culprit for phpmyadmin too, as there are some of those:

```
$ find . -name .gitignore -type f | xargs cat | grep '^!'
!/.gitignore
!/dot.gif
!/original/
!/pmahomme/
!/metro/
```

So there's three directories "original", "pmahomme" and "metro" for which the old bug may have been triggered. I cannot try to reproduce your exact problem, as I have no way of using nodegit right now. So could you please let us know which files you are seeing as "new" which should in fact have been ignored? If these are files in one of those three directories, then the bug is already fixed for the upcoming release.

**Comment by williamdes** [comment] 2018-12-21 08:58
@pks-t The files only appear after `npm run css-compile`
```
william@williamdes:/mnt/Dev/phpmyadmintest$ find . -name .gitignore -type f | xargs cat | grep '^!'
!/.gitignore
!/dot.gif
!/original/
!/pmahomme/
!/metro/
!/cache
!/generated
!.*
!.*
!.*
!/**/.idea
```
![Files](https://user-images.githubusercontent.com/7784660/50333736-8d4bab80-0506-11e9-8700-12a265ee25c8.png)

Thank you for helping me !

**Comment by pks-t** [comment] 2019-01-23 12:32
Yeah, it's exactly those directories I have expected: "metro", "original" and "pmahomme". So the bug should already have been fixed via #4670. I'll propose to include it in the next bugfix release v0.27.8, but it'll definitely be included in v0.28.

Please feel free to reopen this issue if you see that those upcoming releases did _not_ fix your problem.

**Closed by pks-t** 2019-01-23 12:32 UTC

**Comment by ethomson** [comment] 2019-01-23 12:45
Yeah let's bring that into 0.27.8 if it's not in the fixes that I cherry-picked already?

**Comment by pks-t** [comment] 2019-01-23 13:07
It's not :) I've added a comment in #4942
