### ISSUE TITLE
Windows: While cloning it fails to create directories because multiple new directories are passed to _wmkdir routine

### ISSUE THREAD

**Issue by kkutsner** [libgit2/libgit2#2849] opened 2015-01-26 08:15 UTC
I'm trying to launch libgit based application using Jenkins on some slave node. So when it does clone, it uses **D:\path\to\repo** as local path parameter, but only **D:\path** is exists on slave's node. Libgit fails to create 'to\repo' folder until 'to' folder is created manually. This issue is not reproducible when you run the same application on local machine (out-of-Jenkins environment).

Looking under debugger I see that `p_mkdir()` function internally uses `_wmkdir()` which accepts only one new directory. As a result, I see that full path is passed to `_wmkdir()` with several multiple directories:
 - Expected value: **\\\\?\D:\path\to**
 - Actual value: **\\\\?\D:\path\to\repo**

The main question is it assumed that `_wmkdir()` will create all new directories? Can somebody check what values are passed to `_wmkdir()`?

**Comment by ethomson** [comment] 2015-01-26 16:11
Are you certain that your permissions allow whomever is running Jenkins to create `D:\path\to`?

If `D:\path\to` is getting created successfully when you're *not* running in Jenkins, and it *fails* when you are running in Jenkins, it strongly suggests that the difference is Jenkins.

**Comment by carlosmn** [comment] 2015-01-26 16:26
The one-dir-at-a-time limitation is the same across most OSs, so libgit2 does take that into consideration; if it works locally for you it's highly unlikely that this is the issue.

You haven't mentioned what the error message from libgit2/OS is. As @ethomson said, if it only happens when running as jenkins, permissions are the most likely culprit, but without an error message,  we can only guess what the issue might be.

**Comment by kkutsner** [comment] 2015-01-26 16:36
@ethomson The permissions looks OK since it is started up using granted user.
The command  `mkdir D:\path\to` works OK under Jenkins. The command `mkdir D:\path\to\repo` does not work under Jenkins because only `D:\path` in the case. 

My concern is that `_wmkdir()` should not be used to create nested directories according to MSDN doc and under debugger I see that libgit tries to create nested directories using simple single call to  `_wmkdir()`. For some reasons it works when libgit app is running from console, but it does not work when running under Jenkins.

**Comment by kkutsner** [comment] 2015-01-26 16:40
@carlosmn I'm getting following error:
Failed to make directory `D:\path\to\repo`: The system cannot find the path specified

**Comment by ethomson** [comment] 2015-01-26 16:45
By only analyzing what you're seeing in the debugger, I suspect that you're missing the interactions with the filesystem *before* calling `_wmkdir`.  We're not expecting it to create leading directories, [we call a function](https://github.com/libgit2/libgit2/blob/master/src/repository.c#L1434) called `git_futils_mkdir` that is intended to [do this for us](https://github.com/libgit2/libgit2/blob/master/src/fileops.c#L383).

This code was refactored pretty heavily recently - are you certain that you're using the same libgit2 between this desktop app and Jenkins?

**Comment by kkutsner** [comment] 2015-01-26 17:02
@ethomson Yeah, I see this stuff, it looks like it does not work as expected. My desktop app is just called from Jenkins. Jenkins here is just my application launcher on some remote node...

Just figured out that I use 0.22.0 and there is more recent release is available. I definitely will try it now and get back to if it is still reproducible

**Comment by ethomson** [comment] 2015-01-26 17:08
Okay, I would be interested to know the outcome.

**Comment by kkutsner** [comment] 2015-01-27 09:42
Updated version works in the same way. I just [figured out](https://github.com/libgit2/libgit2/blob/master/src/fileops.c#L387) that helper which unwinds the path uses `/` separator, but the input path was previously canonized to use `\` as path separator.  

So when I passed unix style path as an input to my program the issue disappeared. That is not obvious that the library accepts only unix style paths only. Did I missed anything?

I added trace code to see what values are passed to `_wmkdir` under Jenkins and I got following calls when passed unix style path 'to/repo' as an input parameter:
*Trying to create path: to*
*Trying to create path: to/repo*
*Trying to create path: to/repo/.git*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/objects*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/objects/info*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/objects/pack*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/refs*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/refs/heads*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/refs/tags*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/hooks*
*Trying to create path: D:/JN-S/workspace/to/repo/.git/info*
*Success*
And below is list of calls when I passed 'to\repo' path:
*Trying to create path: to\repo*
*Error: Failed to make directory 'to\repo': The system cannot find the path specified.*

**Comment by kkutsner** [comment] 2015-02-01 12:38
@ethomson @carlosmn Guys, what do you think about the investigation above? Is this something that need to be fixed in the library or the client should preprocess file path to convert all file path separators to unix style?

**Comment by ethomson** [comment] 2015-02-03 18:25
@kkutsner Can you provide some code that illustrates this problem, please?  The Windows-type functions generally use `\\?\C:\Foo` style drive letters.  The internal, git-type functions generally use POSIX style paths.  It's possible that something's not doing the appropriate translation, but without being able to capture this in a reproducible case, I can't guess as to where.

**Comment by kkutsner** [comment] 2015-02-09 21:26
@ethomson Ok. I'm slammed, but I'll do it later

**Comment by ethomson** [comment] 2015-02-18 17:38
I believe this was fixed with #2880.  If this still fails for you, please reopen this with some additional details about how to repro.  Thanks!

**Closed by ethomson** 2015-02-18 17:38 UTC
