### ISSUE TITLE
libssh2 on Linux always returns error upon calling `libssh2_userauth_list()`

### ISSUE THREAD

**Issue by theseion** [libgit2/libgit2#3382] opened 2015-08-15 06:58 UTC
On an Ubuntu 12.04 I am unable to use libssh2. Calling `libssh2_userauth_list()` (e.g. during `git_clone()`) always make libssh2 report `Would block requesting userauth list`.
I can confirm that libssh2 also reports that the used session is in blocking mode (and forcing the session to be blocking again does not change anything).

I've tested this with libssh2.1.4.3 and libssh2.1.6.0, with libgit2.0.23.0.

IRC conversation for reference: 

maxleske: Hi. I’m facing an issue with libssh2 on Linux. The same code works flawlessly on OSX. The problem occurs when I try to perform “upload_pack” with github (due to a simple git_clone call). libssh2 always returns “Would block requesting user auth list”.
[5:03pm] maxleske: Interestingly I can get it to partially work when stepping with gdb. But then there are timing problems, so I don’t get much further
[5:03pm] maxleske: maxleske: any ideas?
[5:08pm] cmn: sounds like libssh2 is in non-blocking mode
[5:09pm] cmn: which is weird, since we should be setting it to blocking as soon as we can
[5:10pm] cmn: which versions are you using?
[5:14pm] maxleske: cnm: libgit2 v0.23 and libssh2 v1.0.1
[5:16pm] icedtia4 joined the chat room.
[5:18pm] maxleske: cnm: I’ll compile libgit2 again and add a line where I explicitly set blocking mode again. See if that changes anything
[5:18pm] maxleske: thanks
[5:19pm] maxleske: (wow, and I can’t read… it’s cmn, not cnm)
[5:20pm] cmn: that seems like a really old version of libssh2
[5:20pm] cmn: which may or may not have different blocking defaults, iirc the docs don't actually specify which it is, and I think we assume it starts out blocking
[5:20pm] cmn: which may be a bad idea, but it seems to work generally
[5:22pm] maxleske: um I think I gave you the wrong version number. the so version is 1.0.1, but the source version is 1.4.3
[5:22pm] maxleske: sorry
[5:30pm] maxleske: i can confirm that libssh2_session_get_blocking() reports that it’s in blocking mode. forcibly setting the blocking mode again has no effect
[5:30pm] icedtia4 left the chat room. (Remote host closed the connection)
[5:40pm] cmn: if libssh2 says it's in blocking mode bur reports that an operation didn't succeed because it would block, that's a bug in libssh2
[5:40pm] cmn: can you try with libssh2 1.6?
[5:41pm] maxleske: sure

**Comment by carlosmn** [comment] 2015-08-15 15:51
And it still looks like a libssh2 bug. Have you asked them/looked for this bug in their bug lists?

**Comment by theseion** [comment] 2015-08-15 15:53
Yes, it does :). No, I haven't yet but was going to. I opened the issue anyway since other people might want to know that this is being worked on.

**Comment by carlosmn** [comment] 2016-03-23 10:40
Closing this one as a dupe of #3563 since that one has more information about why this happens.

**Closed by carlosmn** 2016-03-23 10:40 UTC
