### ISSUE TITLE
Unable to push just a commit to a remote (instead of a reference)

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3849] opened 2016-07-02 17:56 UTC
I'm trying to do the equivalent of `git push {remote} {commit}:{branch}` in libgit2, but I when I call `git_remote_upload()` with a refspec like `e9c46cd9071113c95f6b3fb48b74f98056abf7a1:refs/heads/master`, it fails with this error:

> No such reference 'e9c46cd9071113c95f6b3fb48b74f98056abf7a1'

Am I doing something wrong or is this feature simply not supported? Is there any workaround?

**Comment by ethomson** [comment] 2016-07-05 14:51
No - unfortunately this is not supported.  I think that this should not be a terribly difficult fix (see also #3178).  The only workaround that I can imagine is setting up a temporary reference and pushing that, but that's obviously a bummer.

**Comment by carlosmn** [comment] 2016-07-06 21:02
Indeed, this is a dupe of #3178 and potentially also #1125.

**Closed by carlosmn** 2016-07-06 21:02 UTC
