### ISSUE TITLE
HTTPS proxy support with curl

### ISSUE THREAD

**Issue by FatalEnigma** [libgit2/libgit2#4515] opened 2018-02-07 10:30 UTC
### Reproduction steps
Configured a local squid instance to run https with a self signed cert.
Passed this https url for the proxy settings and attempting a clone a github repo 
### Expected behavior
Connection should establish through proxy and allow cloning.
### Actual behavior
code is quitting with the exception:
"curl socket is no longer valid"
### Version of libgit2 (release number or SHA1)
libgit2 version 0.25.1
### Operating system(s) tested
centos-release-6-8.el6.centos.12.3.x86_64

I couldn't find anywhere which stated whether https proxies are supported at this point in time or not. Is this simple a limitation of libgit right now?

**Comment by FatalEnigma** [comment] 2018-02-07 11:22
After repeating testing with v26.0 in a fresh environment I am now getting:
SSL error: received early EOF

**Comment by ethomson** [comment] 2018-11-28 20:34
Oops, sorry, SSL proxies are _not quite_ supported yet.  Reopening.

**Comment by josebalius** [comment] 2019-02-12 15:46
@ethomson What is the status for HTTPS support? Anything I can do to help this move forward? If nothing has been started, I would be interested in contributing.

**Comment by ethomson** [comment] 2019-02-12 16:15
Hi @josebalius, we did some heavy duty refactoring of our HTTP mechanisms in #4870.  We removed curl as a dependency and modularized things a bit.  This means that we can (in theory) both create an HTTP _or_ HTTPS connection to a proxy, and tunnel through it with `CONNECT`.

I also updated our test proxy implementation to be able to support HTTPS so that we could validate this in our CI runs.  *However* I removed the CI tests before shipping because I was seeing valgrind complaints when testing this in our CI infrastructure.  I was _not_ seeing these complaints in my setup with a more modern version of Ubuntu.  Given that, I _suspect_ that the problem is re-entrance problems in the older version of OpenSSL.  But it's also possible that we're just not setting something up right, or defaults changed in newer versions of OpenSSL, etc.

I just created the [`ethomson/https_proxy` branch](https://github.com/libgit2/libgit2/tree/ethomson/https_proxy) and opened #4975 which brings those tests back.  If you want to take a look and see how or if things are working, that would be awesome.

Note that I thought that I _also_ removed the ability to connect to an HTTPS proxy (basically just `if`d it right out) since those valgrind warnings made me uneasy.  But I don't see that immediately in a diff, so either it's just hard for me to see amidst lots of refactoring, or I convinced myself that it worked on modern systems and we could safely ship it.

At the very least, though, we should determine if valgrind is giving us credible warnings, and if so, what version(s) of OpenSSL we should support for HTTPS proxies.

**Comment by josebalius** [comment] 2019-02-12 16:21
@ethomson Thank you! I will take a look at the branch and see what I find.

**Comment by ethomson** [comment] 2019-02-12 16:24
Cool.  Note that I did disable HTTPS proxies in 52478d7dc323ad1768bc5c6fc03c031b7adc5d20.  I reverted that in my `https_proxy` branch.  (Note that I force-pushed, sorry I did that after pointing you to my branch, it's a habit.)

**Comment by ethomson** [comment] 2019-06-11 13:50
Fixed via #5052

**Closed by ethomson** 2019-06-11 13:50 UTC
