### ISSUE TITLE
Infinite loop with SSH agent and GIT_EAUTH

### ISSUE THREAD

**Issue by asandroq** [libgit2/libgit2#3471] opened 2015-10-15 15:37 UTC
When using `git_cred_ssh_key_from_agent` for creating credentials the authentication is non-interactive. Looking at the code here https://github.com/libgit2/libgit2/blob/master/src/transports/ssh.c#L590 we can see that if `_git_ssh_authenticate_session` returns `GIT_EAUTH` this will loop indefinitely and make the SSH agent eat all the CPU cycles.

**Comment by carlosmn** [comment] 2015-10-19 15:31
That loop hands control back to the calling application to decide what to do next. If the application gives libgit2 an authentication method to try, libgit2 will use it.

**Comment by asandroq** [comment] 2015-10-19 15:40
The calling application chose the SSH agent method to get credentials, which will keep failing again. forever.

**Comment by carlosmn** [comment] 2015-10-19 16:51
The application should stop selecting that method if it's going to keep failing.

**Comment by asandroq** [comment] 2015-10-19 19:14
I do not know how I can make this clearer. It is an infinite loop, inside `libgit2`. The application does not have an opportunity to do *anything*. `libgit2` keeps hitting the SSH agent which uses nearly 100% CPU while this is happening. At this point the only thing that can be done is to kill the application. I even gave the location in the source code where this is happening, and where I fixed my local copy of `libgit2`.

**Comment by ethomson** [comment] 2015-10-21 20:31
If you look at the place in the source code that you pointed out, the application's credential callback should be getting invoked (in `request_creds`).

Your callback certainly *should* be called back again.  Is your credential callback not being invoked?  Is it being invoked and you're returning `GIT_EUSER`?  Are you not providing one and we're failing to return `-1` there?

Can you provide some sort of reproduction case?

**Comment by nkeck720** [comment] 2015-10-26 02:57
I think maybe it is an issue with your code there, @asandroq. The source you showed in the description appears to work for me (Fedora Core 5, distro make/gcc packages; also Cygwin under Windows 10, and finally Pelles C IDE under Windows 10). As @ethomson noted you should be getting called back again.

**Comment by ethomson** [comment] 2015-11-13 16:50
I'm going to go ahead and close this, since we don't have reproduction steps.  Please followup if you can provide code to reproduce this.

**Closed by ethomson** 2015-11-13 16:50 UTC
Labels: needs repro
