### ISSUE TITLE
Client cert support

### ISSUE THREAD

**Issue by jjpe** [libgit2/libgit2#4204] opened 2017-04-13 16:14 UTC
On [this libgit2sharp issue](https://github.com/libgit2/libgit2sharp/issues/1152#issuecomment-279966002) thread it is mentioned that this project has no support for client certificates at this time. 
I am interested in adding support for this, but am not sure what it needed to achieve it. By submitting this as an issue here I'm hoping to discuss the issue and avoid any potential duplicated effort.

### Reproduction steps
Try to clone any project with some application that uses libgit2 to achieve it, from a server that asks for a client certificate. Some concrete examples of this are [neon](https://github.com/neon-bindings/neon) and [npm](https://github.com/npm/npm).
I'm assuming at this point that the same behavior holds for e.g. a `pull` as well as any other functionality that require interaction with a `remote`.

### Expected behavior
I'd like the clone, pull etc to succeed.

### Actual behavior
At this moment the exact error varies a bit depending on the actual application but it comes down to the server not authenticating the client application due to a missing certificate.

### Version of libgit2 (release number or SHA1)
Any, as I'm discussing new functionality.

### Operating system(s) tested
Windows, OS X, Ubuntu Linux

**Comment by LordNali** [comment] 2017-05-18 16:14
We'd like to participate or at least support this discussion. Is this feature (request) so unique - many companies I know are you using git repositories with client certificates.

**Comment by pks-t** [comment] 2017-05-19 08:56
The problem is probably not about unique-ness, but simply that nobody had enough interest and/or time yet to implement this. We'd certainly welcome pull requests implementing this feature.

**Comment by jjpe** [comment] 2017-05-20 16:27
I have no patches atm, mainly because I'm not sure what's needed conceptually to make this work.

To avoid the X/Y problem, let me state that my real goal is this: I need to be able to use tools like [cargo](https://github.com/rust-lang/cargo)* and [neon](https://github.com/neon-bindings/neon)** in such a way that dependencies located on a GitHub Enterprise server*** resolve as neatly as on github.com or the respective repositories (e.g. [crates.io](https://crates.io) for Cargo). 

* Cargo uses libgit2
** Neon uses Cargo internally
***This GitHub Enterprise server has its own certificates

**Comment by ethomson** [comment] 2017-05-20 16:34
@jjpe To clarify:  your GitHub Enterprise server "has its own certificates" (ie, it's using a self-signed certificate or a certificate that's signed by your company's CA which isn't trusted)?

Your GitHub Enterprise server is _also_ configured to require _client_ certificates?  Ie, your IT department has delivered you a certificate that you use to authenticate to the server, and the server identifies you after your client provides its certificate to the server?

Can you provide one or more of the error messages that you get when you try to perform a server operation?

**Comment by jjpe** [comment] 2017-05-25 10:51
The certs signed by an associate company, so I suppose that could be called self-signed. It's still validated through one of COMODOs root certs though, in practice it's a chain of 3 certs including the root cert and an intermediate cert.

Anything that wants to talk to the GHE server needs to have the certificate installed, including workstations. For example, my machine has the cert in its certificate store.
However, it happens that [Cargo](https://github.com/rust-lang/cargo), the rust-lang default build tool which uses `libgit2`, cannot clone and update on the build slave, even though the host has the certificate installed. This has been verified by doing a manual `git clone` and `git pull` from the same GHE server, which succeeds without issue.

**Comment by ethomson** [comment] 2017-05-25 11:04
Okay - this is not a _client_ certificate...  so that's not what this issue is about.

It's not appropriate to do tech support in a feature request - especially an unrelated one.  😀

Are you certain that your server is delivering the cert chain correctly?  And are you certain that this is actually a libgit2 problem and not cargo?  If so, open a bug report in a separate issue.  Please include a healthy amount of details like what platform you're on.

**Comment by jjpe** [comment] 2017-05-25 11:17
I'm not looking for tech support, I encountered a real-world issue I need solved ;)

I'm fairly sure. As I said, CLI git (which, as I understand it, doesn't use libgit2) can access the GHE server without issue from the same build slave, so I don't see how a misconfiguration could be the cause.
[This](https://github.com/rust-lang/cargo/issues/3993) is the original Cargo issue that got the ball rolling. Before I open a new issue, could you please read it and tell me what you think?

**Comment by ethomson** [comment] 2017-05-25 11:24
This suggests a cargo issue.  I'll follow up in that bug.

**Comment by vadixidav** [comment] 2019-02-07 20:54
I had the same issue and filed a bug on Cargo. The issue the person above has is the same as mine and isn't related to the other Cargo issue which is linked above. I can't say whether or not this is a libgit2 issue at this time, but please see the Cargo issue I opened on Cargo: rust-lang/cargo#6642. This issue only happens on Windows where libgit2 is being used and not on Linux.

**Comment by ethomson** [comment] 2019-02-07 21:25
It might be interesting to see the HTTP handshake, but fundamentally, libgit2 doesn't support client certificates.

That this works on Linux suggests that this is not a server requirement.  So WinHTTP may have an option that can disable client certificates that we need to set.  There may be a `WinHttpSetOption` that you can use to turn this off.

Unfortunately, I don't really understand this problem, nor do I have a configuration that replicates this problem to test against.

**Comment by ethomson** [comment] 2019-06-11 13:54
I've never seen a git server that asks for a client certificate, even on-prem Azure DevOps Services.  This is not a priority for any maintainer at the moment.  Pull requests would be welcome, but I'm closing this issue.

**Closed by ethomson** 2019-06-11 13:54 UTC
