### ISSUE TITLE
fatal error: xlocale.h: No such file or directory

### ISSUE THREAD

**Issue by utkarsh2102** [libgit2/libgit2#5454] opened 2020-03-13 19:51 UTC
Hi,

While building libgit2 0.99.0 in Debian, I get the following error:
```
Run Build Command(s):/usr/bin/make cmTC_ebb77/fast && make[2]: Entering directory '/<<PKGBUILDDIR>>/build-debian-release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_ebb77.dir/build.make CMakeFiles/cmTC_ebb77.dir/build
make[3]: Entering directory '/<<PKGBUILDDIR>>/build-debian-release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ebb77.dir/CheckSymbolExists.c.o
/usr/bin/cc   -D_GNU_SOURCE -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -fvisibility=hidden -fPIC -Wno-missing-field-initializers -Wstrict-aliasing -Wstrict-prototypes -Wdeclaration-after-statement -Wshift-count-overflow -Wunused-const-variable -Wunused-function -Wint-conversion -Wformat -Wformat-security    -o CMakeFiles/cmTC_ebb77.dir/CheckSymbolExists.c.o   -c /<<PKGBUILDDIR>>/build-debian-release/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/<<PKGBUILDDIR>>/build-debian-release/CMakeFiles/CMakeTmp/CheckSymbolExists.c:3:10: fatal error: xlocale.h: No such file or directory
    3 | #include <xlocale.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/cmTC_ebb77.dir/build.make:66: CMakeFiles/cmTC_ebb77.dir/CheckSymbolExists.c.o] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/build-debian-release/CMakeFiles/CMakeTmp'
make[2]: *** [Makefile:121: cmTC_ebb77/fast] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/build-debian-release/CMakeFiles/CMakeTmp'
```

Looks like `xlocale.h` has been removed in `glibc 2.26`.

See:

- https://www.linuxquestions.org/questions/slackware-14/no-luck-with-libc-on-current-xlocale-h-missing-4175612648/
- https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27

**Comment by ethomson** [comment] 2020-03-13 19:53
Looks like a cmake issue?  It's trying to build `CheckSymbolExists.c`, which I think is part of cmake itself?

**Comment by utkarsh2102** [comment] 2020-03-13 20:04
Hm, is it?
I am not sure how to have this fixed, honestly.
The configuration I am using is this: https://salsa.debian.org/debian/libgit2/-/blob/master/debian/rules

Any clue how to go about it?

**Comment by utkarsh2102** [comment] 2020-03-13 20:05
On another note,
```
➜  libgit2 git:(master) ✗ grep -irnw "xlocale.h"
src/regexp.c:156:# include <xlocale.h>
src/CMakeLists.txt:117:	CHECK_SYMBOL_EXISTS(regcomp_l "regex.h;xlocale.h" HAVE_REGCOMP_L)
```

Do we really need these? Can't we get rid of xlocale.h completely?

**Comment by ethomson** [comment] 2020-03-13 21:30
> Do we really need these? Can't we get rid of xlocale.h completely?

I don't know.  Probably not universally, but maybe on some platforms.  Do you have `regcomp_l` but not `xlocale.h`?

For this cmake problem, you're right - I think that we should be able to detect `recomp_l` even if `xlocale.h` doesn't exist.

In the meantime, if you don't have `regcomp_l` then you can specify the `REGEX_BACKEND`.

**Comment by utkarsh2102** [comment] 2020-03-14 16:26
Hi,
> In the meantime, if you don't have regcomp_l then you can specify the REGEX_BACKEND.

Is there a way to do so by passing something to cmake options?

**Comment by pks-t** [comment] 2020-03-14 17:03
On Sat, Mar 14, 2020 at 09:26:52AM -0700, Utkarsh Gupta wrote:
> > In the meantime, if you don't have regcomp_l then you can specify the REGEX_BACKEND.
> 
> Is there a way to do so by passing something to cmake options?

Yes, you can. Just pass "cmake -DREGEX_BACKEND=$YOUR_BACKEND" to CMake,
where $YOUR_BACKEND may be one of "regcomp_l", "pcre2", "pcre",
"regcomp" or "builtin".

**Comment by utkarsh2102** [comment] 2020-03-14 17:57
> Yes, you can. Just pass "cmake -DREGEX_BACKEND=$YOUR_BACKEND" to CMake, where $YOUR_BACKEND may be one of "regcomp_l", "pcre2", "pcre", "regcomp" or "builtin".

Thank you, @pks-t.
While trying with `pcre2`, I get the following error:
```
/usr/bin/ld: CMakeFiles/cmTC_564eb.dir/CheckFunctionExists.c.o: in function `main':
/usr/share/cmake-3.16/Modules/CheckFunctionExists.c:17: undefined reference to `qsort_s'
```

Any clue what's wrong?

**Comment by pks-t** [comment] 2020-03-14 18:35
On Sat, Mar 14, 2020 at 10:58:04AM -0700, Utkarsh Gupta wrote:
> > Yes, you can. Just pass "cmake -DREGEX_BACKEND=$YOUR_BACKEND" to CMake, where $YOUR_BACKEND may be one of "regcomp_l", "pcre2", "pcre", "regcomp" or "builtin".
> 
> Thank you, @pks-t.
> While trying with `pcre2`, I get the following error:
> ```
> /usr/bin/ld: CMakeFiles/cmTC_564eb.dir/CheckFunctionExists.c.o: in function `main':
> /usr/share/cmake-3.16/Modules/CheckFunctionExists.c:17: undefined reference to `qsort_s'
> ```
> 
> Any clue what's wrong?

I really don't know, but something seems to be awfully broken with your
CMake installation. First the errors about the regex backend, which
shouldn't happen as we try to auto-detect available backends. Now the
problem with `qsort_s`, which is also auto-detected via CMake's
`CHECK_FUNCTION_EXISTS()`. And as @ethomson noted, the errors happen in
CMake's modules itself, not in our code. So basically it seems like the
detection of available functions via CMake is broken on your system.

I'm puzzled. Do you by any chance have some very special environment? Do
you maybe set up specific CFLAGS or something like that, have a special
compiler?

**Comment by pravi** [comment] 2020-03-14 18:42
Its cmake 3.16.3 and clean debian unstable (using sbuild). I also got the qsort_s missing error.

**Comment by utkarsh2102** [comment] 2020-03-14 19:00
> I'm puzzled. Do you by any chance have some very special environment? Do
you maybe set up specific CFLAGS or something like that, have a special
compiler?

It's equally confusing to me as well.
I maintain libgit2 in Debian (see https://tracker.debian.org/pkg/libgit2). The 0.28.4 version built smoothly. However, when trying to upgrade to 0.99.0, this problem started to appear.
Did something related change/patched in this release? I could very well open a bug against cmake in Debian, but only after being sure that this is indeed a bug in CMake.

**Comment by pks-t** [comment] 2020-03-14 19:19
On Sat, Mar 14, 2020 at 11:43:04AM -0700, Pirate Praveen Arimbrathodiyil wrote:
> Its cmake 3.16.3 and clean debian unstable (using sbuild). I also got the qsort_s missing error.

I just set up a Debian Unstable VM to try and reproduce, but everything
works as expected with CMake v3.16.3. Did you try building with CMake
directly instead of using sbuild? If that works I suspect that sbuild
sets up some variables that interfere with CMakes build system, but I'd
be happy to check if you provide reproduction instructions with sbuild.

**Comment by pks-t** [comment] 2020-03-14 19:28
On Sat, Mar 14, 2020 at 12:00:37PM -0700, Utkarsh Gupta wrote:
> It's equally confusing to me as well.
> 
> I maintain libgit2 in Debian (see
> https://tracker.debian.org/pkg/libgit2). The 0.28.4 version built
> smoothly. However, when trying to upgrade to 0.99.0, this problem
> started to appear.
>
> Did something related change/patched in this release? I could very
> well open a bug against cmake in Debian, but only after being sure
> that this is indeed a bug in CMake.

We've got about nearly 50 patches touching our CMake build instructions,
so there's definitely quite a lot of commits that could've caused this.
If it were the regex backend only, then I'd not be too surprised as
we've restructured selection of these backends with v0.99. But I don't
think we've touched anything that could relate to the `qsort_s` issue.

If I were able to reproduce, then I could trivially run a bisect and
identify the breaking commit. But given that I'm not able to do that
with Debian Unstable and plain CMake, that's a non-starter
unfortunately, except if you can do that.

**Comment by utkarsh2102** [comment] 2020-03-16 10:54
>Did you try building with CMake
directly instead of using sbuild? If that works I suspect that sbuild
sets up some variables that interfere with CMakes build system, but I'd
be happy to check if you provide reproduction instructions with sbuild.

It even fails for a local build. 
`sbuild` doesn't do anything, but just builds a package in a clean environment.

There are probably two ways to check:

1. Spawn up a Debian Unstable (Sid) container/VM and clone the 0.99.0 release and try to build with cmake (in the Debian archive). Let us know how it goes?

2. For building the Debian package:
- Spawn up a Debian Unstable (Sid) container/VM.
- Run `apt install devscripts git-buildpackage quilt libgit2`
- Clone the git repository of libgit2's Debian package via `gbp clone --pristine-tar https://salsa.debian.org/debian/libgit2`
- `cd libgit2`
- Run `origtargz` to generate the tarballs`
- Run `apt build-dep libgit2` to install the build dependencies of libgit2.
- Run `dpkg-buildpackage -uc -us` (the build command) -- this should take you to the `qsort_s` issue we're getting. 

Let me know if you get stuck somewhere, I'll be happy to help! :)

> If I were able to reproduce, then I could trivially run a bisect and
identify the breaking commit. But given that I'm not able to do that
with Debian Unstable and plain CMake, that's a non-starter
unfortunately, except if you can do that.

Thank you so much for your help so far! Really appreciated! :heart:

**Comment by pks-t** [comment] 2020-03-16 12:52
On Mon, Mar 16, 2020 at 03:54:38AM -0700, Utkarsh Gupta wrote:
> There are probably two ways to check:
> 
> 1. Spawn up a Debian Unstable (Sid) container/VM and clone the 0.99.0 release and try to build with cmake (in the Debian archive). Let us know how it goes?

That's exactly where my confusion comes from: I _did_ check this on
Debian Unstable and couldn't reproduce. Did I miss any magic sauce or
options you've passed to it? Is it maybe caused by any packages missing
or being present?

> 2. For building the Debian package:
> - Spawn up a Debian Unstable (Sid) container/VM.
> - Run `apt install devscripts git-buildpackage quilt libgit2`
> - Clone the git repository of libgit2's Debian package via `gbp clone --pristine-tar https://salsa.debian.org/debian/libgit2`
> - `cd libgit2`
> - Run `origtargz` to generate the tarballs`
> - Run `apt build-dep libgit2` to install the build dependencies of libgit2.
> - Run `dpkg-buildpackage -uc -us` (the build command) -- this should take you to the `qsort_s` issue we're getting. 

Maybe I'll have to try this as soon as I find the time to do so.

**Comment by utkarsh2102** [comment] 2020-03-16 13:11
> That's exactly where my confusion comes from: I _did_ check this on Debian Unstable and couldn't reproduce. Did I miss any magic sauce or options you've passed to it? Is it maybe caused by any packages missing or being present?

If you couldn't reproduce it this way, then it means that it might be a problem at our side (either dependency issue or problem with cmake, or whatever).

> Maybe I'll have to try this as soon as I find the time to do so.

Thank you! This should confirm what the issue is.

**Comment by pks-t** [comment] 2020-03-22 16:00
Finally found some time to try and reproduce, and in fact I can when using sbuild. There's two problems:

1. You do not have libpcre2-dev as build dependency
1. You're deleting the "deps/" folder when generating the source tarball. It did grow a new dependency, though, which is the ntlmclient one. You can either stop deleting the folder or pass "-DUSE_NTLMCLIENT=OFF" to CMake.
1. We've switched over the default to use our own copy of http-parser bundled in the "deps/" folder, which doesn't work either cause you're deleting that folder. We did fix some bugs in http-parser (see https://github.com/nodejs/http-parser/pull/483) which isn't accepted upstream yet, thus we highly recommend to use our own bundled version. If you still want to use upstream, you can pass "-DUSE_HTTP_PARSER=system" to use the system-installed one instead.

This mostly fixes the build, except for one bug we have with how we set up the libgit2.pc file, which was fixed already via #5412.

**Comment by utkarsh2102** [comment] 2020-03-22 20:01
Hi @pks-t,

This is just awesome! :heart: 

```
--- a/debian/rules
+++ b/debian/rules
@@ -25,6 +25,8 @@ override_dh_auto_configure:
                -DTHREADSAFE:BOOL=ON \
                -DBUILD_CLAR:BOOL=ON \
                -DREGEX_BACKEND=pcre2 \
+               -DUSE_NTLMCLIENT=OFF \
+               -DUSE_HTTP_PARSER=system \
                -DLIB_INSTALL_DIR:STRING=lib/$(DEB_HOST_MULTIARCH)
 
        dh_auto_configure --builddirectory=build-debian-devel -- \
@@ -37,6 +39,8 @@ override_dh_auto_configure:
                -DBUILD_CLAR:BOOL=OFF \
                -DBUILD_SHARED_LIBS:BOOL=OFF \
                -DREGEX_BACKEND=pcre2 \
+               -DUSE_NTLMCLIENT=OFF \
+               -DUSE_HTTP_PARSER=system \
                -DLIB_INSTALL_DIR:STRING=lib/$(DEB_HOST_MULTIARCH)
 
```
+ #5412 fixes the build!
Thank you so much for your help!

Re: using `deps/`, someone removed it on purpose, not sure what. I'll check that soon! :)

**Comment by pravi** [comment] 2020-03-23 04:16
We prefer to use packaged dependencies instead of embedded copies hence removing deps.

**Comment by pks-t** [comment] 2020-03-23 07:03
On Sun, Mar 22, 2020 at 09:16:27PM -0700, Pirate Praveen Arimbrathodiyil wrote:
> We prefer to use packaged dependencies instead of embedded copies hence removing deps.

I can definitely relate. As we're using a patched http-parser
dependency, though, it is expected that certain functionality will fail
when using an unpatched system one (see the linked PR @ethomson opened
upstream). So my recommendation would be to either use our bundled one
or to patch Debian's http-parser package.

**Comment by pks-t** [comment] 2020-03-23 10:49
I'm closing the issue as we got it building now. Thanks again for your report and collaboration!

**Closed by pks-t** 2020-03-23 10:49 UTC

**Comment by utkarsh2102** [comment] 2020-03-23 14:57
Thanks, @pks-t, for all your help!
