### ISSUE TITLE
Ignoring of similarity metric for blob objects with equal oids

### ISSUE THREAD

**Issue by gumenikav** [libgit2/libgit2#4387] opened 2017-10-24 16:34 UTC
I have noticed that custom similarity metric are ignored if blob objects have identical oids in similarity_measure function:
```cpp
	/* check OID match as a quick test */
	if (git_oid__cmp(&a_file->id, &b_file->id) == 0) {
		*score = 100;
		return 0;
	}
```
I think, that since custom similarity metric is used, equality of oids doesn't mean equality of objects.

**Comment by ethomson** [comment] 2017-10-24 16:46
Yes, this is by design so that we avoid unnecessary work when objects are obviously identical.

Is this a theoretical problem you're raising?  Or are you actually running into this as a problem?  If so, could you explain a little bit about what you're doing and how you're using a custom similarity metric?

Any change here has the potential to decimate performance.  So if you're actually wanting a different behavior then we would need to tread very carefully indeed.

**Comment by gumenikav** [comment] 2017-10-24 17:55
I am not sure, may be it`s a theoretical problem. There is an insufficient information about possibilities of similarity metric. May be it would be enough to modify documentation about it, because initially i supposed, that i can override whole similarity mechanism.

In my store, name of blob object cannot change. So, i defined similarity metric according to blob names. If names of blob objects are the same, objects are the same. And I use this metric for diff operation. But, when i have two objects with equal oid, this approach stops to work. I make diff in my client application, and instead of expected  two different entries(delete/add), i see rename.

So, my similarity metric works only in one and half way, translating add/delete to modify/rename and modify to add/delete.

For now, i analyze diff results for rename entries to handle this situation. But it looks like duct tape for me, that`s why i am here.

**Comment by ethomson** [comment] 2019-02-18 10:51
I'm closing this issue since it's been a while; I'd be willing to review a PR that added some option to disable identical oids as being seen as identical objects, but this seems far enough outside the normal use case that I don't think it's a generally useful option that I intend to implement it myself.

**Closed by ethomson** 2019-02-18 10:51 UTC
