### ISSUE TITLE
Examples fail to build on windows

### ISSUE THREAD

**Issue by cjhoward92** [libgit2/libgit2#4385] opened 2017-10-23 16:51 UTC
### Reproduction steps
Build `libgit2` with examples on:

```
mkdir build
cmake .. -DBUILD_EXAMPLES=ON
cmake --build .
```

### Expected behavior
For the examples to build

### Actual behavior
I get an error
```
"C:\Dev\libgit2\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Dev\libgit2\build\examples\cgit2.vcxproj" (default target) (11) ->
(Link target) ->
  common.obj : error LNK2019: unresolved external symbol _getline referenced in function _cred_acquire_cb [C:\Dev\libgit 2\build\examples\cgit2.vcxproj]
  C:\Dev\libgit2\build\examples\Debug\cgit2.exe : fatal error LNK1120: 1 unresolved externals [C:\Dev\libgit2\build\exam ples\cgit2.vcxproj]

    22 Warning(s)
    2 Error(s)
```
### Version of libgit2 (release number or SHA1)
[Current master](https://github.com/libgit2/libgit2/commit/8f05d2d81643177ce44d1449a551ef206b18cd5e) at `8f05d2d81643177ce44d1449a551ef206b18cd5e`

### Operating system(s) tested
Windows 10 build 15063 (I tried on another windows 10 machine, too, but I do not know the build. It also failed)

**Comment by carlosmn** [comment] 2017-11-04 16:08
What compiler/VS version are you using? It works in CI so there's something different in your setup.

**Comment by cjhoward92** [comment] 2017-11-04 16:52
I will need to verify, but on one machine I have the 2013 C++ redistributables, and on the other I think it is 2015 or 2017. I am not sure if there is a precedence on the newer versions or not. Is there a way I can look at the CI configuration? Will the `appveryor.yaml` have everything I need?

**Comment by carlosmn** [comment] 2017-11-04 18:40
The appveyor file shows what rules we follow for building, including what we tell CMake to use. In Appveyor itself you can see the details of what was using in the VMs, e.g. at https://ci.appveyor.com/project/libgit2/libgit2/build/3983

**Comment by cjhoward92** [comment] 2017-11-04 18:46
I will check it out when I get home and see if I can't get it working. Thanks!

**Comment by pks-t** [comment] 2017-11-06 11:15
I think AppVeyor doesn't build examples at all. I'll create a PR which fixes that, including the getline stuff if it comes up

**Comment by pks-t** [comment] 2017-11-06 19:38
This should be fixed by #4397 now. Please verify the issue is resolved and close this ticket if so. Thank you :)

**Comment by cjhoward92** [comment] 2017-11-07 14:54
@pks-t They build just fine! The only issue I have now is that they crash saying they cannot find the git2.dll. I am not sure if this is a configuration issue on my machine, though. Do I need to install git2 to have the examples work or can I use another build flag to have the examples look for the built version of git2? Or, rather, should they work fine as is?

**Comment by pks-t** [comment] 2017-11-09 20:52
This has something to do with how Windows locates libraries when a program is being run and is nothing we can solve on our site. Easiest would be if you just copied the git2.dll into the example directory.

**Comment by pks-t** [comment] 2017-11-09 20:55
Closing this now as the original issue has been resolved. Thanks again for your report!

**Closed by pks-t** 2017-11-09 20:55 UTC

**Comment by cjhoward92** [comment] 2017-11-09 20:59
Yeah, after I copied the `dll` over everything seemed to be working fine! Thanks!
