### ISSUE TITLE
Filter API should support streaming

### ISSUE THREAD

**Issue by joshaber** [libgit2/libgit2#2757] opened 2014-12-11 15:45 UTC
The current filter API design uses `git_buf` which requires that both the input and output in their entirety live in memory. When either are big, this is less than ideal.

It'd be great if it could support streaming.

**Comment by carlosmn** [comment] 2015-01-05 12:27
>I was under the impression that we wouldn't need to "stage" or "commit" large files, as the point of a large asset manager is that we would work the the SHA1 of the large file and the actual contents would be streamed from somewhere else. Is that correct?

Even when the output is just a hash and a bit of metainformation, we would currently still load the whole large file into memory for the filter to run (or that's how I understand it), so we'd only be storing it once, but we'd be using a large chunk of memory to do so.

I don't think we're that far away from being able to support streaming in a few important places (supporting it everywhere would obviously be more work). We already have the `git_odb_stream` interface, and we used to allow using unknown sizes. If we bring it back, we can at least try to make this use-case somewhat efficient, by using a spill-buffer and `sendfile(2)` where it's available (or whatever Windows has); which should be a better implementation than that of someone who's trying to solve a different problem when they're dealing with the filter.

If we make a filter's apply function be a constructor for an object which implements `git_odb_stream` we should be able to support streaming into the filter with just a few changes in libgit2 (but see #2786 about just passing the filename). Or we could pass the filename and a `git_odb_stream` to the filter which it can use for output (combined with the previous, this should allow easy chaining).

**Comment by ethomson** [comment] 2015-01-05 16:58
Naively, I would agree that streaming is probably not out of reach.

I don't love having a filter read a file and populate the `git_buf` - it seems that reading (and, consequently, writing) files really shouldn't be the filter's job, but more importantly, this seems optimized for the git-media case where you have a very large file in the working directory and you will end up filtering it to a very small file that can easily fit in memory.  As @carlosmn points out, this scenario will mean that you'll put that large file into memory in the general case.

I'm sympathetic to an argument that you usually *wouldn't* be filtering a large file *except* with a git-media-like filter, and so I've been sort of waffling on how I feel about this for a few days.  But I do remain concerned about the ability to chain filters -- it seems useful to me to be able to use (for example) git-media along with another filter (say, git-crypt).

**Comment by arrbee** [comment] 2015-01-05 17:39
> Naively, I would agree that streaming is probably not out of reach.

It is not infeasible, but I believe it is a lot more code. While I was initially writing the filtering code, I tried out a couple of versions to support streaming, and it is complicated in the general case. The issue is that you have to allow each filter to be invoked multiple times and you need to manage the flow of data between them. Each filter has different streaming requirements, for example `media` will have to iterate over the entire file before it can produce output (in either direction), `crlf` can operate incrementally, but has a number of buffer edge cases, and `crypt` can operate incrementally (I believe) but may have various block size limits. In combination, if `media` is operating on the output of `crypt` and you don't want to stage the entire crypted file in memory, then you need a multi-invocation producer-consumer model. Certainly not infeasible, but a lot more code.

I understand that the asymmetry of making reading the file from disk a special case feels wrong, but it is a real boundary of the filter pipeline &mdash; there is only one time that you read the bytes from disk in the working directory. If we had a general streaming implementation, I'd be fine with saying "the first filter is a streaming reader internal to libgit2 that can flexibly read the bytes on-demand" and then allowing the rest of the pipeline to just consume and produce. However, I honestly believe that is a much larger project.

I'd like to solve the pragmatic problem of filtering for big files on disk where there is significant decimation of the data. Obviously this is targeted at supporting large media filtering, but that is an important case, I think.

I do think we can eliminate one glaring asymmetry here and make is so that this doesn't operate just in the `TO_ODB` direction. We can allow the same flag to apply for the `TO_WORKTREE` direction and enable it for the cases where `git_filter_list_apply_to_blob` is used (i.e. don't preload the blob into memory and allow the streaming ODB APIs to be used instead). That is a little tricky because of how I designed the API (assuming that the `git_blob` was already loaded), but making this take the `git_odb *` and a `const git_oid *` instead to support streaming is a manageable amount of work.

(Speaking of which, as you know, I have pretty little time to code these days, so if a full streaming API is going to be required to make #2786 acceptable, then I'll have to look for someone else to work on it.)

**Comment by ethomson** [comment] 2015-01-05 17:48
I wonder if an interesting compromise to allow multiple filters may be to allow filters to always use files on both the input and output side - that is to say that if a filter wants to deal with "big files" then they will be given a file location to read from and a file location to write to (or maybe file descriptors or what not) instead of a `git_buf`.

> I do think we can eliminate one glaring asymmetry here and make is so that this doesn't operate just in the TO_ODB direction.

I think that this would be nice, indeed.

**Comment by arrbee** [comment] 2015-01-05 18:01
> I wonder if an interesting compromise to allow multiple filters may be to allow filters to always use files on both the input and output side - that is to say that if a filter wants to deal with "big files" then they will be given a file location to read from and a file location to write to (or maybe file descriptors or what not) instead of a git_buf.

So, this is similar in concept to what I started to write. My intent was that the `git_filter_source` object would become the focus of input (and output) for the filters. Instead of using a `git_buf`, the filter would get an input `git_filter_source` which supported a `git_filter_source_read()` function to read data and then could invoke some sort of writing callback to (that could either stream out to an intermediate file on disk, or into a in-memory buffer, or be passed along to the input of a downstream filter).

Would it meet your suggestion to replace the `GIT_FILTER_DONT_PRELOAD_WORKDIR` with a `GIT_FILTER_USE_FILE_INPUT` and `GIT_FILTER_USE_FILE_OUTPUT` as options that indicate the filter will expect the data to be on disk and the `git_buf *` should come in containing the full resolved path to the file on disk (instead of the contents) and/or the output `git_buf *` will be filled with the path to a file containing the filtered data (instead of the filtered data itself)? This could work, although I think it would have to be paired with a new parameter to the `cleanup` callback so that the temp filename is available for the filter to clean up.

**Comment by ethomson** [comment] 2015-01-06 16:37
I think that's cool.  I was thinking that maybe we'd just have one flag that was `USE_FILE_IO` or something that indicated that you'd get files *or* buffers, but that extra granularity of buffers in files out might be useful (particularly in a git-media like situation).  I confess that I haven't thought about this as deeply as you have.  Whichever makes the most sense.

**Comment by carlosmn** [comment] 2015-02-20 09:12
#2911 has taken on the brunt of this, and we do now support streaming in the filters. We do however still require a blob to be loaded in memory before processing it when checking out, but that's a limitation we can't get over for many objects.

**Comment by ethomson** [comment] 2015-04-18 00:38
I'm going to close this, as I feel like we delivered what was requested.  Doing better and trying to never put big blobs into memory (say, during checkout) is going to require some Advanced Trickery and I think should be dealt with in a separate issue...  People should be using git-lfs for big files anyway.  Thanks everybody!

**Closed by ethomson** 2015-04-18 00:38 UTC
