### ISSUE TITLE
refspec including git commits don't work

### ISSUE THREAD

**Issue by uzytkownik** [libgit2/libgit2#4353] opened 2017-09-18 02:51 UTC
It seems that refspec including full commits, such as `+a1594642cb617b189356192639c05d07f80bc5ff:refs/heads/master` don't work.

I know I can WAR by crating a temporary tag but given that commandline supports it it would seem a logical thing to have.

PS. It would be nice if I could just manually give OID instead of constructing manually refspec strings only for libgit2 to get it back. Something like:

```
int git_remote_push_oid(      git_remote       *remote,
                        const git_strarray     *target,
                        const git_oid          *source,
                        const git_push_options *opts);
```

**Comment by carlosmn** [comment] 2017-10-29 10:17
Indeed, they don't; but this is a duplicate of #3178 or #1125.

As far as passing an oid directly into the push function, we go with what git considers to be the inputs to push, which is a string that describes what you are trying to achieve.

**Closed by carlosmn** 2017-10-29 10:17 UTC
