### ISSUE TITLE
pushing commit sha1 directly doesn't work

### ISSUE THREAD

**Issue by MrHacky** [libgit2/libgit2#3178] opened 2015-06-03 09:33 UTC
normal git allows pushing a commit by its sha1 by using a refspec like this:
    "d03e40c8bbb7d2b4d6b53dd34f22805c1cee209c:refs/heads/master"

While libgit2 does seem to parse such refspecs, it still fails to work.

I think the cause is in push.c:calculate_work which uses git_reference_name_to_id which doesn'work on a sha1.

**Comment by carlosmn** [comment] 2015-06-03 10:38
This would be a duplicate of #1125

**Comment by MrHacky** [comment] 2015-06-03 12:04
sort of...  #1125 seems to be about wildcard refscpecs, though the title is indeed generic enough it could encompass this one.

**Comment by Piedone** [comment] 2016-04-05 23:47
Specifically libgit2 will return the error "No such reference '<commit hash>'". It seems that there is no way to push single commits with libgit2.

**Comment by ethomson** [comment] 2024-03-09 21:26
Fixed via #6362

**Closed by ethomson** 2024-03-09 21:26 UTC
Labels: needs repro
