### ISSUE TITLE
Please help: how to stash hunks & lines?

### ISSUE THREAD

**Issue by demian85** [libgit2/libgit2#2412] opened 2014-06-08 22:35 UTC
I found someone that is willing to help me with libgit2 bindings for NodeJS and as my knowledge of this lib if very limited, I'm looking for help on which functions need to be implemented in order to achieve the 'patching' functionality, currently only available by executing `git add -p`.

I opened many issues in git-related node modules but no one could help me at all. This is one of my issues: https://github.com/nodegit/nodegit/issues/146

Can someone please help/orient me?

**Comment by carlosmn** [comment] 2015-01-09 10:36
Closing as a dupe of #591

**Closed by carlosmn** 2015-01-09 10:36 UTC
