### ISSUE TITLE
Error -1/5: error inflating zlib stream (Reproducer included)

### ISSUE THREAD

**Issue by rralf** [libgit2/libgit2#5899] opened 2021-05-30 17:54 UTC
Hi,

I posted the following bugreport first for pygit2, and it turned out to be a bug of libgit2. Check out my previous bug report here:
https://github.com/libgit2/pygit2/issues/1076

### Reproduction steps

Try to test the following code on this repo 
$ git clone https://lore.kernel.org/netdev/0

```
#include <git2.h>
#include <stdio.h>

int main(void)
{
        git_repository *repo = NULL;
        git_tree_entry *entry = NULL;
        git_commit *commit = NULL;
        git_tree *tree = NULL;
        git_blob *blob = NULL;
        const git_error *e;
        git_oid oid;
        int error;

        git_libgit2_init();

        error = git_repository_open(&repo, ".");
        if (error)
                goto err;

        error = git_oid_fromstr(&oid, "7c260769a628415a753e77d16b56900c5df3a5c8");
        if (error)
                goto err;

        error = git_commit_lookup(&commit, repo, &oid);
        if (error)
                goto err;

        error = git_commit_tree(&tree, commit);
        if (error)
                goto err;

        error = git_tree_entry_bypath(&entry, tree, "m");
        if (error)
                goto err;

        if (git_tree_entry_type(entry) != GIT_OBJECT_BLOB)
                goto err;

        error = git_blob_lookup(&blob, repo, git_tree_entry_id(entry));
        if (error)
                goto err;

        git_tree_entry_free(entry);
        puts(git_blob_rawcontent(blob));

        return 0;
err:
        e = git_error_last();
        printf("Error %d/%d: %s\n", error, e->klass, e->message);
        return error;
}
```

### Expected behavior

Successful execution

### Actual behavior

Error -1/5: error inflating zlib stream

### Version of libgit2 (release number or SHA1)

1.1.0

### Operating system(s) tested

Arch Linux

**Comment by lhchavez** [comment] 2021-05-31 02:20
duplicate of #5590 (meaning: this is fixed on the tip-of-tree `main` branch)

**Closed** 2021-05-31 02:20 UTC

**Comment by rralf** [comment] 2021-05-31 10:44
Thanks for pointing to the duplicate!
Will there be a new Release soon? This Bug has been present since a long while.
