### ISSUE TITLE
git_checkout_head FORCE | REMOVE_UNTRACKED doesn't remove untracked files in a subdirectory

### ISSUE THREAD

**Issue by segevfiner** [libgit2/libgit2#5089] opened 2019-05-27 14:53 UTC
### Reproduction steps
1. Save:

**main.c**:
```c
#include <stdio.h>
#include <git2.h>

int main(int argc, char *argv[]) {
	git_libgit2_init();	

	if (argc != 3) {
		fprintf(stderr, "Usage: ...");
		return 2;
	}

	git_repository *repo = NULL;
	int error = git_repository_open(&repo, argv[1]);
	if (error < 0) {
		const git_error *e = giterr_last();
		fprintf(stderr, "Error %d/%d: %s\n", error, e->klass, e->message);
		return 1;
	}

	git_checkout_options opts = GIT_CHECKOUT_OPTIONS_INIT;
	opts.checkout_strategy = GIT_CHECKOUT_FORCE | GIT_CHECKOUT_REMOVE_UNTRACKED;
	char *paths[] = {argv[2]};
	git_strarray paths_arr = {paths, 1};
	opts.paths = paths_arr;

	error = git_checkout_head(repo, &opts);
	if (error < 0) {
		const git_error *e = giterr_last();
		fprintf(stderr, "Error %d/%d: %s\n", error, e->klass, e->message);
		return 1;
	}
}
```

**run.sh**:
```sh
#!/bin/sh
set -e

gcc -g main.c -lgit2 -o discard-test

echo Preparing
rm -rf test-repo
git init test-repo
cd test-repo
mkdir code
touch code/run code/foo
git add code/run
git commit -m "Add code/run"

echo Before
git status

cd ..
./discard-test test-repo code/foo
cd test-repo

echo After
git status
```

2. Run `run.sh`. Tweak the gcc line as needed to get the example to compile.

(The example leaks memory, it's just an example, real code should free stuff of course)

### Expected behavior
"code/foo" is removed.

### Actual behavior
"code/foo" remains untouched.

### Version of libgit2 (release number or SHA1)
ac070afecc33e9f263353455debd07876b0e91bf

### Operating system(s) tested
Xubuntu 18.04.2 x86_64
macOS 10.14.5

**Comment by ethomson** [comment] 2019-05-27 15:15
Did you mean this line:

```
char *paths[] = {argv[1]};
```

to look at `argv[2]` instead of `argv[1]`?  The code, as posted, will _definitely_ ignore `code/foo`, since you have specified paths to checkout and `code/foo` is not a part of them.

**Comment by segevfiner** [comment] 2019-05-27 15:20
> Did you mean this line:
> 
> ```
> char *paths[] = {argv[1]};
> ```
> 
> to look at `argv[2]` instead of `argv[1]`? The code, as posted, will _definitely_ ignore `code/foo`, since you have specified paths to checkout and `code/foo` is not a part of them.

Whoops. Yeah it should be that. I will fix the PR description. The bug still reproduces with `argv[2]` fix. I had it hard-coded previously and changed it to `argv` for the MWE but made a mistake.

**Comment by segevfiner** [comment] 2019-05-27 15:26
It might be caused by this line: https://github.com/libgit2/libgit2/blob/b1e286254a17fe2801979cd6d1f64eac77b2801d/src/checkout.c#L2580

**Comment by tiennou** [comment] 2019-05-27 15:28
Tentative Clar testcase:
```
void test_checkout_head__untracked_subdir_removal(void)
{
	git_repository *repo = NULL;
	git_checkout_options co_opts = GIT_CHECKOUT_OPTIONS_INIT;
	char *paths[] = {"code/foo"};
	git_strarray paths_arr = {paths, 1};
	git_status_options stat_opts = GIT_STATUS_OPTIONS_INIT;
	status_entry_counts counts;
	static const char *paths_before[] = {
		"code/foo",
	};
	static const unsigned int statuses_before[] = {
		GIT_STATUS_WT_NEW,
	};
	static const char *paths_after[] = {
		"code/bar",
		"code/foo",
	};
	static const unsigned int statuses_after[] = {
		GIT_STATUS_WT_NEW,
		GIT_STATUS_WT_NEW,
	};

	memset(&counts, 0x0, sizeof(status_entry_counts));
	counts.expected_entry_count = 1;
	counts.expected_paths = paths_before;
	counts.expected_statuses = statuses_before;

	cl_git_pass(git_repository_init(&repo, "test-repo", 0));
	cl_must_pass(p_chdir("test-repo"));
	cl_must_pass(git_futils_creat_withpath("code/run", 0777, 0777));
	cl_must_pass(git_futils_creat_withpath("code/foo", 0777, 0777));

	system("git add code/run");
	system("git commit -m \"Add code/run\"");

	/* Before */
	stat_opts.flags = GIT_STATUS_OPT_DEFAULTS | GIT_STATUS_OPT_RECURSE_IGNORED_DIRS;

	cl_git_pass(git_status_foreach_ext(repo, &stat_opts, cb_status__normal, &counts));

	cl_assert_equal_i(counts.expected_entry_count, counts.entry_count);
	cl_assert_equal_i(0, counts.wrong_status_flags_count);
	cl_assert_equal_i(0, counts.wrong_sorted_path);

	/* Checkout */
	co_opts.checkout_strategy = GIT_CHECKOUT_FORCE | GIT_CHECKOUT_REMOVE_UNTRACKED;
	co_opts.paths = paths_arr;

	cl_git_pass(git_checkout_head(repo, &co_opts));

	/* After */
	memset(&counts, 0x0, sizeof(status_entry_counts));
	counts.expected_entry_count = 2;
	counts.expected_paths = paths_after;
	counts.expected_statuses = statuses_after;

	cl_git_pass(git_status_foreach_ext(repo, &stat_opts, cb_status__normal, &counts));

	cl_assert_equal_i(counts.expected_entry_count, counts.entry_count);
	cl_assert_equal_i(0, counts.wrong_status_flags_count);
	cl_assert_equal_i(0, counts.wrong_sorted_path);

	git_repository_free(repo);
}
```

Do check, because I still haven't actually run the original…

**Comment by segevfiner** [comment] 2019-05-27 15:40
I think `paths_after` is supposed to be empty for the correct result but will be like `paths_before` with the bug. Didn't run the proposed test (Not in front of my computer), just from a cursory look.

**Comment by segevfiner** [comment] 2019-05-27 17:53
Here is a simple failing test for this:
```c
void test_checkout_head__do_remove_untracked_paths(void)
{
	git_checkout_options opts = GIT_CHECKOUT_OPTIONS_INIT;
	git_index *index;

	cl_git_pass(p_mkdir("testrepo/tracked", 0755));
	cl_git_pass(p_mkdir("testrepo/tracked/subdir", 0755));
	cl_git_mkfile("testrepo/tracked/tracked", "tracked\n");
	cl_git_mkfile("testrepo/tracked/untracked", "untracked\n");

	cl_git_pass(git_repository_index(&index, g_repo));
	cl_git_pass(git_index_add_bypath(index, "tracked/tracked"));
	cl_git_pass(git_index_write(index));

	git_index_free(index);

	opts.checkout_strategy = GIT_CHECKOUT_FORCE | GIT_CHECKOUT_REMOVE_UNTRACKED;
	char *paths[] = {"tracked/untracked"};
	opts.paths.strings = paths;
	opts.paths.count = 1;
	cl_git_pass(git_checkout_head(g_repo, &opts));

	cl_assert(git_path_isfile("testrepo/tracked/tracked"));
	cl_assert(!git_path_isfile("testrepo/tracked/untracked"));
}
```

**Comment by ethomson** [comment] 2019-05-28 07:07
> Whoops. Yeah it should be that. I will fix the PR description. The issue still reproduces with the argv[2] fix. I had it hard-coded previously and changed it to argv for the MWE but made a mistake.

Awesome.  Thanks.  I had assumed that given the very nice reproduction steps that it was a typo in the repro steps, not something deeper.  (But I wasn't in front of my computer to repro it.)

**Comment by extrawurst** [comment] 2020-04-28 11:54
What is the state of this @ethomson ? Can it be merged?

**Closed** 2020-05-10 23:18 UTC
