### ISSUE TITLE
Lack of nanosecond values from fs_iterator makes git_diff_tree_to_workdir (and _with_index) very slow

### ISSUE THREAD

**Issue by CmdrMoozy** [libgit2/libgit2#3169] opened 2015-06-01 18:36 UTC
In diff.c, if the stat data looks different for two files, then we recalculate the new item's OID to see whether or not the file really changed. On Linux, `GIT_DIFFCAPS_TRUST_NANOSECS` is set, so we include nanosecond values from `struct stat` in this comparison.

However, fs_iterator gets its stat data from `git_index_entry__init_from_stat`, which currently does not set the `mtime.nanoseconds` and `ctime.nanoseconds` fields in the `git_index_entry`. The result is that we recalculate the OID for **all** new items in the diff, which is (relatively speaking) very slow.

I'm more than willing to write a patch for this, but I wanted to discuss potential solutions first. Is simply populating those fields in `git_index_entry__init_from_stat` only if we detect that we're on a POSIX OS a reasonable solution?

For reference, here are the offending lines in the current master:

[diff.c lines 833-842](https://github.com/libgit2/libgit2/blob/master/src/diff.c#L833-L842)
[iterator.c line 1311](https://github.com/libgit2/libgit2/blob/master/src/iterator.c#L1311)
[index.c lines 732-746](https://github.com/libgit2/libgit2/blob/master/src/index.c#L732-L746)

**Comment by CmdrMoozy** [comment] 2015-06-01 20:07
[This patch](https://github.com/libgit2/libgit2/compare/libgit2:master...CmdrMoozy:nsec_fix) fixes the problem for me, and it builds properly on at least Linux and Windows.

**Comment by nulltoken** [comment] 2015-06-01 20:14
@CmdrMoozy Could you please open a pull request from this patch so that the CI servers kick in?

**Comment by CmdrMoozy** [comment] 2015-06-01 21:53
@nulltoken Done. A unit test needed to be updated as well, but now this change seems to be passing CI.

**Comment by ethomson** [comment] 2015-06-01 22:10
I think that - [like git itself](https://github.com/git/git/blob/master/Makefile#L219-L223) - we should actually have a conditional here and it should default to off.  In the absence of this setting, we should not try to bother testing the nanoseconds field at all, which is (unless you recompiled your git) probably what you want to match its behavior.

**Comment by carlosmn** [comment] 2015-06-01 23:25
We can't trust the OS and filesystem to give us accurate nanosecond data. git itself references a particular glibc version, which is something that'd be hard to check for, and that command includes a warning about ext3 which should still be quite widely used, and there's a bunch of other filesystems which may or may not support it.

Some filesystems on Windows do provide it, though AFAICT git itself does not make use of it, so the situation would be similar to the more unixy systems.

**Comment by CmdrMoozy** [comment] 2015-06-02 14:34
I've updated my pull request to add a CMake option which enables/disables nanosecond comparisons (off by default). I sort of like the idea of still making that information available in `git_index_entry` if the platform supports it, and just not checking it in diff.c if `GIT_USE_NSEC` is disabled. However, this does mean that we depend on glibc >= 2.12 and linux >= 2.5.48 (at least according to `man 2 stat` on my machine).

**Comment by carlosmn** [comment] 2015-06-02 18:16
The linux requirement doesn't sound too onerous, but I do agree it should be off by default.

The nanosecond information has space in the index entries already so we should be filling it in from the index regardless. We have `git_libgit2_features()` so we can expose this compile-time setting through there as well if consumers are interested.

**Comment by CmdrMoozy** [comment] 2015-06-02 18:47
No reason not to expose the setting. I've added a couple extra commits which add GIT_FEATURE_NSEC and update the associated unit test.

**Comment by kblees** [comment] 2015-06-05 19:32
AFAICT, timestamps on Windows are accurate. I can dig up the respective patches for Git for Windows and resend them upstream again (see https://github.com/msysgit/git/pull/314).

On Linux, there is probably a bug that file times in the inode cache are not properly rounded to on-disk precision (i.e. file times may change if the cache is flushed and re-read from disk). This is why nanosecond filetimes are disabled in upstream Git (described in Documentation/technical/racy-git.txt).

This bug was supposedly fixed with patch "Sync in core time granularity with filesystems" in kernel 2.6.11. But I suspect that the rounding optimization in `kernel/time/time.c::timespec_trunc` is broken as of introduction of high resolution timers in kernel 2.6.16. This would affect all file systems with resultions > 1ns and != 1s.

I can reproduce the rounding issue with FAT on Linux due to its 2 second mtime resolution (i.e. touching a file may result in an mtime with odd seconds, which will later change to even seconds). I wasn't able to reproduce this with NTFS though (Linux seems to round to 1µs rather than the 100ns on-disk precision, even though struct super_block.s_time_gran == 100 for NTFS...).

**Comment by CmdrMoozy** [comment] 2015-06-08 15:09
Anything else needed from me to get this fix merged? The pull as it stands right new seems to pass CI, barring an unrelated "Error: Failed to download resource "openssl"" Travis error. I don't see an easy way to tell Travis to retry the build on that platform.

**Comment by carlosmn** [comment] 2015-11-12 19:04
The aforementioned pull request has been merged to master.

**Closed by carlosmn** 2015-11-12 19:04 UTC
