### ISSUE TITLE
segfautlt in git_worktree_lookup on bare repos

### ISSUE THREAD

**Issue by Richard-Mathie** [libgit2/libgit2#4822] opened 2018-10-01 10:57 UTC
From libgit2/pygit2#814 we hit a segfault when looking up worktrees on bare repos, even if a worktree has been checked out in another directory.

### Reproduction steps
Running using pygit2 bindings...
```
$ git init --bare bare
$ git --git-dir=bare update-ref refs/heads/develop `echo first | git --git-dir=bare commit-tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904`
$ git --git-dir=bare worktree add versions/develop develop
$ python -c "import pygit2; pygit2.Repository('bare').lookup_worktree('develop')"
Segmentation fault (core dumped)
```
### Version of libgit2
0.27.1

### Operating system(s) tested
linux

**Comment by tiennou** [comment] 2018-10-01 22:16
This looks like #4630, which I don't think is in a released version yet.

**Comment by pks-t** [comment] 2018-10-04 07:53
Yeah, I expect that the issue is fixed already. I'm closing this issue -- please feel free to re-open it in case we're mistaken. Thanks for your report!

**Closed by pks-t** 2018-10-04 07:53 UTC

**Comment by jdavid** [comment] 2018-10-06 09:34
Ok, I see it has not yet been backported to `maint/v0.27` and v0.28 not yet released
