### ISSUE TITLE
High memory utilization while cloning large repos

### ISSUE THREAD

**Issue by ravindp** [libgit2/libgit2#2738] opened 2014-12-01 07:45 UTC
I tried cloning a repo with about 3 million objects and noticed that memory utilization by the clone API increases linearly throughout the clone process till a max value of ~700MB. I had a chat with @ethomson on this earlier and it seems like a bug in LibGit2. We have an object cache but the size of cache is capped to 256MB. Ideally we should see the memory usage capped closer to 256MB but that's not what I found in my experiments (Attached memory utilization graph) 

![image](https://cloud.githubusercontent.com/assets/9804129/5242593/0e226b8a-795c-11e4-8fa2-8169d4e8aa15.png)

This is on Windows.

**Comment by carlosmn** [comment] 2015-04-18 16:50
@ravindp have you had a chance to check how much of the memory utilisation which is reported comes from mapping the packfile?

**Comment by carlosmn** [comment] 2015-06-05 20:23
Since there's been no updates for quite a while and I do still believe that the graph is measuring total address space used, I'm going to close this.

If you an reproduce this behaviour whilst making sure to only measure the heap usage, do reopen.

**Closed by carlosmn** 2015-06-05 20:23 UTC
