### ISSUE TITLE
Performance regression in `revwalk` API

### ISSUE THREAD

**Issue by maxbrunsfeld** [libgit2/libgit2#4740] opened 2018-07-26 21:38 UTC
### Explanation

Atom uses libgit2's `revwalk` API to compute the number of commits by which the user's current branch is 'ahead' and 'behind' its corresponding remote branch. After upgrading from libgit2 0.24 to 0.26, we're seeing this code take a long time to execute, even when the branch is up-to-date with its remote (no commits ahead or behind).

### Reproduction steps

1. Clone the [Atom](https://github.com/atom/atom) repository

1. Create a C file called `test.c` with this content:

```c
#include "git2.h"
#include <stdio.h>
#include <assert.h>

unsigned count_commits_between_refs(
  git_repository *repo,
  const char *ref1,
  const char *ref2
) {
  git_oid oid1, oid2;
  assert(git_reference_name_to_id(&oid1, repo, ref1) == GIT_OK);
  assert(git_reference_name_to_id(&oid2, repo, ref2) == GIT_OK);

  git_oid merge_base;
  assert(git_merge_base(&merge_base, repo, &oid1, &oid2) == GIT_OK);

  git_revwalk *revwalk;
  assert(git_revwalk_new(&revwalk, repo) == GIT_OK);

  git_revwalk_push(revwalk, &oid1);
  git_revwalk_hide(revwalk, &oid2);

  unsigned result = 0;
  git_oid current_commit;
  while (git_revwalk_next(&current_commit, revwalk) == GIT_OK) result++;
  git_revwalk_free(revwalk);

  return result;
}

int main() {
  git_libgit2_init();

  git_repository* repo;
  assert(git_repository_open_ext(&repo, getenv("PWD"), 0, NULL) == GIT_OK);

  for (unsigned i = 0; i < 50; i++) {
    const char *ref1 = "refs/heads/master";
    const char *ref2 = "refs/remotes/origin/master";

    unsigned ahead_count = count_commits_between_refs(repo, ref1, ref2);
    unsigned behind_count = count_commits_between_refs(repo, ref2, ref1);
    printf("%u ahead, %u behind\n", ahead_count, behind_count);
  }

  return 0;
}
```

3. Compile this program against the branch of libgit2. Side note: when trying to build libgit2 on macOS, I had trouble linking against openssl. So I build the static libraries using our node.js wrapper module: [git-utils](https://github.com/atom/git-utils) and compiled against them like this:

```sh
clang                  \
  -I libgit2/include   \
  zlib.a               \
  http_parser.a        \
  git2.a               \
  test.c
```

4. Run this program

### Expected behavior

The program should exit immediately, outputting "0 ahead, 0 behind" repeated 50 times.

### Actual behavior

The program takes 4 seconds to run.

### Version of libgit2 (release number or SHA1)

The head of master as of today: 42f8384045ca325c6885be21a89c3d8027995e03. I was also able to reproduce this against libgit2 0.26.0.

The problem does *not* happen with libgit2 0.24.0.

### Operating system(s) tested

Mac OS 10.13.16

/cc @carlosmn

**Comment by ethomson** [comment] 2018-07-27 09:05
> Compile this program against the branch of libgit2. Side note: when trying to build libgit2 on macOS, I had trouble linking against openssl. So I build the static libraries using our node.js wrapper module: git-utils and compiled against them like this:

We would encourage you not to use OpenSSL on macOS, but to use SecureTransport, macOS's built-in libraries.

**Comment by maxbrunsfeld** [comment] 2018-07-27 16:37
> We would encourage you not to use OpenSSL on macOS, but to use SecureTransport, macOS's built-in libraries.

Good to know; I wasn't specifically trying to use OpenSSL; I just got a linker error with a bunch of undefined symbols that looked like OpenSSL APIs when I built libgit2 using the default steps and tried to use it in my example program.

Also, I just saw https://github.com/libgit2/libgit2/issues/4428. It looks like this may actually be a duplicate of that issue. Feel free to close as a dup or leave open if you think the different repro steps are helpful in any way.

**Comment by ethomson** [comment] 2018-07-27 16:42
> Good to know; I wasn't specifically trying to use OpenSSL; I just got a linker error with a bunch of undefined symbols that looked like OpenSSL APIs when I built libgit2 using the default steps and tried to use it in my example program.

Right - sorry to hijack the thread.  I recall that nodegit explicitly up the libgit2 build to use OpenSSL.

> Also, I just saw #4428. It looks like this may be a duplicate of that issue. Feel free to close this as a dup or leave it open if you think the different repro steps are helpful in any way.

I suspect this is a dup but I'll leave it open until we run them both down in case it's not.

**Comment by neithernut** [comment] 2018-09-06 08:06
Testing with this reproducer and the libgit2-repository, I do measure a small difference in performance (below 5%). But I doubt that that's the cause of the regression described.

In a related issue (#4736), it was already established that the regression was introduced by a rewrite of the revwalk code (6708618c10f509ed1d22298628bf578a514d2624). The working hypothesis is that the root cause is the same for #4736 and #4428. This issue was, in fact, created to express what the root cause may be.

If I'm not wrong, the problem is rooted in revwalk semantics: due to the feature of hiding an OID and all it's ancestors, the entire history of all commits involved must be considered. Currently, this is done inside `git_revwalk_next()` and the results are cached. Hence, the first call scales with `O(N)`, where N is the number of commits in the repository.

I planned on moving this complexity into `git_revwalk_hide()` and friends and adding a `git_revwalk_limit()` which does not take into account ancestry (as proposed by @pks-t in #4428), hopefully making `git_revwalk()` an `O(1)`- or `O(log(N))`-operation again (with `N` being cached hidden OIDs). However, this was a month ago and I evidently did not find the time to prepare a PR, yet. So if anybody want's to pick it up...

**Comment by carlosmn** [comment] 2018-09-17 11:42
It's left a bit to be assumed, but in your example, are `refs/heads/master` and `refs/remotes/origin/master` at the same commit? It does seem perfectly believable that we would have a regression where there isn't actually anything to walk.

**Comment by neithernut** [comment] 2018-09-17 11:53
Yes, the regression is visible with both refs pointing to the same commit. Well, at least it was when I ran the reproducer(s), e.g. a month ago.

**Comment by carlosmn** [comment] 2018-09-17 12:02
Right, OK, then the regression is what I thought, we're walking all the way back because the new ported code fails to recognise that we've run out of uninteresting commits.

**Comment by carlosmn** [comment] 2018-09-17 12:29
Well it turns out to be a sign issue...

When we're comparing the timestamps to see if things are still interesting, we start off with `~0ull` except we were assigning it to a signed integer which meant `-1` and thus the starting value was always earlier than every commit, making us think every commit ended up being interesting.

**Comment by neithernut** [comment] 2018-09-17 12:50
Huh. Did not spot it after reading the portion of the code in question several times back then. It looks to me like you are right. I guess I'll run those reproducers again when I'm home again.

**Comment by carlosmn** [comment] 2018-09-17 12:57
I've opened #4809 to fix this.

We've talked about some sort of automated benchmarking for the project, and something like that would have hopefully caught this kind of regression, where the test cases are with small-enough repositories that we wouldn't notice the time difference.

**Closed** 2018-09-18 02:03 UTC
