### ISSUE TITLE
"Too many files open" issue with open repository iterations

### ISSUE THREAD

**Issue by UbikZ** [libgit2/libgit2#2781] opened 2014-12-24 12:24 UTC
Have an issue with my [git-indicator](https://github.com/UbikZ/git-indicator) project.

> Libgit2 versions

* v0.20.0 (precompiled version)
* I test with v0.21.0 and I had the same issue
* I test with the lastest one (v0.21.3) and I get another issue (SSL) but I've not focused myself on the last one.

> Technical operation of **git-indicator**

Need to open / fetch / rev-list *x* repositories each 4 seconds. (to notify the user if there are some diff between local and origin master branch).

> Issue

After several minutes, **-1** error returned for ```git_repository_open_ext``` with ```Could not open '/path/to/repository/.git/config': Too many files open```.

It looks like [2758 issue](https://github.com/libgit2/libgit2/issues/2758) btw except the gc mwindows stuff.

Thank's for the help!

**Comment by ethomson** [comment] 2015-01-09 16:36
Thanks @UbikZ for the details - indeed, I believe that this is a duplicate of #2758 so I'm going to close this issue and we can continue this conversation over there.  Thanks again for reporting this!

**Closed by ethomson** 2015-01-09 16:36 UTC
