### ISSUE TITLE
Error: SSL error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

### ISSUE THREAD

**Issue by b-3-n** [libgit2/libgit2#4644] opened 2018-05-04 12:15 UTC
### Reproduction steps
Unknown. We use nodegit and possibly several threads are cloning and pulling on different repositories at the same time. To avoid any confusion. No two threads ever clone or pull on the same repository. 

### Expected behavior
Can clone or pull repository.

### Actual behavior
Clone and pull fail with 
`Error: SSL error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init`

### Version of libgit2 (release number or SHA1)
We're using nodegit 0.20.3 and thus libgit v0.26.0.

### Operating system(s) tested
Ubuntu 18.04

Our application that uses nodegit/libgit runs for hours and clones/pulls hundreds of repositories successfully before - for no clear reason - the mentioned error occurs. After the error starts occurring nodegit/libgit is not recovering from it

**Comment by ethomson** [comment] 2018-05-04 12:32
How does your application (or, perhaps in this case, nodegit) handle its configuration of OpenSSL's locking?  Does it call [`git_openssl_set_locking`](https://github.com/libgit2/libgit2/blob/89c332e41b12a72d89de40d63bc568c56a2c336a/include/git2/sys/openssl.h#L34) or does it configure OpenSSL's locking itself?

**Comment by pks-t** [comment] 2018-05-04 14:28
We only ever shut down OpenSSL when the last user calls `git_libgit2_shutdown()` (that is, you need to call `git_libgit2_shutdown()` exactly as many times as you've called `git_libgit2_init()`.) What people frequently do is to call these two functions in every thread that uses libgit2, which may make code simpler in some ways, but some subtle races might be encounterd in these scenarios. Most importantly, it could cause us to repeatedly reinitialize libgit2's state, which is kind of unnecessary.

So what might happen here is that you by some mean get an imbalance of these two calls, causing us to deinitialize libgit2 while it is still in use. This is only speculative, but if that is the case that is nothing we can fix on our side. What I'd recommend in that scenario is that you should maybe only globally initialize libgit2 once at the beginning, before spawning threads, and than once at the end, when you don't want to use libgit2 anymore.

Some other scenario might be that you're using OpenSSL functions somewhere outside of libgit2. So if you call `git_libgit2_shutdown()`, we tear down OpenSSL for you, but you might still want to use it somewhere else. Again, the solution would be to only shutdown libgit2 at the very end.

The last possibility is some race I've found between `git_libgit2_init` and `git_libgit2_shutdown`, where we might end up deinitializing state before it has even be initialized. But I think that rather unlikely to be the cause here. Anyway, I've got a PR up for that in #4645

**Comment by b-3-n** [comment] 2018-05-14 17:10
I don't know the internals of nodegit so I'm not sure what's going on. I created an [issue](https://github.com/nodegit/nodegit/issues/1495) for nodegit. 

There is a minimal example triggering the error here: https://github.com/b-3-n/nodegit_debug 

I'd like to leave this issue open until it is clear where the error stems from (nodegit/libgit).

**Comment by graphicore** [comment] 2018-05-15 15:59
I can confirm this. I'm running very similar code as in the minimal example above, also via nodegit(!).

* I'm not using clone or pull, just `Remote.fetch` directly.
* I'm only fetching from GitHub. Could this be GitHub punishing clients for obsessive or "abusive" downloading of many repos at the same time? It's ~ 270 repos for me, with 10 parallel fetches. I found this [vague statment](https://platform.github.community/t/limit-on-cloning-repositories/3672/2) by @kytrinyx (GitHub Staff):
  > here are no hard rate limits on cloning, so you are free to clone as
     much as you’d like. Still, we’d like to ask you to clone at a reasonable
     pace. Cloning a few (2-3-4) repositories in parallel is okay, cloning a
    100 repositories in parallel is not and can be detected as abusive
    behavior by our automated measures.
* The SSL-errors take some time until they get reported  (~ 15 minutes +), like a timeout handling.
* It seems like, with my setup, I get a constant number of SSL-errors per run:
     * Using 10 parallel fetches, I get a total of 7 of these SSL-errors (maybe this is 8 real threads thus `8 - 1 = 7`)
      * with 5 parallel fetches I get 4 SSL-errors.
      * with 3 parallel fetches I get 2 SSL-errors.

  The failing remotes are different, even though, the input order is the same. I only did a small test with 2 runs for each `max_parallel_fetches`. This number seems also constant when the remote refs are already on disk and fetch is only looking for updates.
It seems like the number of SSL-Errors are `max_parallel_fetches - 1`. And one thread is still fetching everything to the end while the rest is blocked.

**Comment by graphicore** [comment] 2018-05-16 12:25
To confirm/follow up my observations:
 * with 2 parallel fetches I see 1 SSL-Error.
 * when I do only one fetch at a time I see no SSL-Errors.

**Comment by ethomson** [comment] 2018-06-04 11:36
@shimont Are you using nodegit as well?

**Comment by romanlab** [comment] 2018-06-06 14:47
We have the same issue and we use nodegit but after a quick investigation we found that the error is a bit misleading. For us the error was caused by running out of space on the machine that ran the docker container. 

We use the overlayFS storage driver and while we clean up after ourselves inside the container, `/var/lib/docker/overlay2` grows in size till the host machine runs out of space and then we get `Error: SSL error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init` consistently till we restart the container, at this point the `overlay2` dir is emptied and the new container runs smoothly.

Deletes for docker is on the roadmap: https://github.com/docker/distribution/blob/master/ROADMAP.md#deletes

some info about the overlay storage driver:
https://docs.docker.com/storage/storagedriver/overlayfs-driver/

If any one else can confirm that this is indeed the issue it'll be much appreciated

**Comment by b-3-n** [comment] 2018-06-06 16:08
I can say for certain that the error can be produced with sufficient disk space available.

**Comment by tiennou** [comment] 2019-01-29 22:54
As a heads-up, #4875 fixes an issue where we would clobber an initialization failure by closing an invalid SSL context.

**Comment by jaripog** [comment] 2021-01-19 09:21
im too facing the same issue

**Comment by ethomson** [comment] 2021-01-19 09:42
Looks like #4875 fixed this!  Sorry @jaripog, you're definitely facing a different issue.

**Closed** 2021-01-19 09:41 UTC
Labels: has-pr
