### ISSUE TITLE
git_checkout_head() doesn't do anything (in practice)

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2864] opened 2015-02-03 08:18 UTC
The doc says:

    * Updates files in the index and the working tree to match the content of
    * the commit pointed at by HEAD.

But since `git_checkout_head()` simply calls `git_checkout_tree()` with a `NULL` tree, the checkout code will use `HEAD` as a baseline and attempts to check out `HEAD` against it. In practice this means, no attempt will be made to touch modified files (whatever the mode) or create missing ones (unless you happen to be `GIT_CHECKOUT_SAFE_CREATE` mode).

As an example, if you move the `HEAD` to a different commit then call `git_checkout_head()` expecting the index and workdir to be updated to reflect the new commit (as per the docs), nothing happens (and there are no errors either of course).

Is there a bug in the implementation, is the doc wrong, or is it really the intended behavior of `git_checkout_head()`?

PS: If the latter, what's the actual and most efficient way using libgit2 to update the index and workdir to match the `HEAD`?

**Comment by clns** [comment] 2016-05-26 06:36
This is a good question:

> What's the actual and most efficient way using libgit2 to update the index and workdir to match the `HEAD`?

Did you find the answer? Maybe doing `git_checkout_tree()` and `git_checkout_index()` would be better than using `git_checkout_head()`?

**Comment by ethomson** [comment] 2016-05-26 06:55
> Is there a bug in the implementation, is the doc wrong, or is it really the intended behavior of git_checkout_head()?

This is absolutely the intended behavior.  `git_checkout_head` is not a shorthand for switching branches.  If you change `HEAD` without first changing the working directory, then your working directory is dirty.  If you tried to do a (safe) checkout then you would have all sorts of checkout conflicts.

This is as true in libgit2 as it is in git.

You could, of course, do a `FORCE` (the equivalent of `git reset --hard`).  But the proper way to switch branches is to check out the target and then update `HEAD`.  (You can see an example in [LibGit2Sharp](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Commands/Checkout.cs#L153).)

I haven't closed this because it seems reasonable that we could update the documentation to better illustrate this.  Pull requests here are welcome.

**Comment by clns** [comment] 2016-05-26 07:09
> But the proper way to switch branches is to check out the target and then update `HEAD`.

You mean something like this? (in case of a detached head)

```c
git_checkout_tree(/** commit **/)
git_repository_set_head_detached(/** commit **/)
```

**Comment by ethomson** [comment] 2016-05-26 07:11
Yes, if you want a detached head then that looks like the right pattern.

**Comment by clns** [comment] 2016-06-01 05:58
There's a (related?) SO question: http://stackoverflow.com/questions/34599073/git2gos-checkouthead-not-updating-the-index

@ethomson If you'd like to take a look at it I would appreciate it.

**Closed** 2016-06-16 06:53 UTC
Labels: documentation, up for grabs
