### ISSUE TITLE
LIBGIT2_VER_REVISION inconsistent for v0.24.1?

### ISSUE THREAD

**Issue by shadowwalkersb** [libgit2/libgit2#3946] opened 2016-09-30 21:48 UTC
The [latest release](https://github.com/libgit2/libgit2/releases/latest) is tagged `v0.24.1`. But, revision number seems to be `0`.

``#define LIBGIT2_VER_PATCH 0`` in https://github.com/libgit2/libgit2/blob/master/include/git2/version.h#L14. So, the library version and the tag are different. This breaks my tests when I check for the library when it is extracted from the GitHub version tag.

**Comment by carlosmn** [comment] 2016-10-01 14:23
It was indeed not updated, but there's nothing we can do about that now. Dupe of #3776.

**Closed by carlosmn** 2016-10-01 14:23 UTC
