### ISSUE TITLE
Bugs in Backbone routing

### ISSUE THREAD

**Issue by fatso83** [libgit2/libgit2#2877] opened 2015-02-05 10:48 UTC
Manually clicking through the documentation to get to [this url](https://libgit2.github.com/libgit2/#v0.21.3/type/git_clone_options) produces different results than actually clicking the url directly. I assume this is due to some bug in the routing in the SPA powering the documentation.

I am posting [the last comment](https://github.com/nodegit/nodegit/issues/330#issuecomment-72902753) in a nodegit issue thread that sums up my findings. You can find lots of information and screen dumps in that thread.

----------

Not sure if I should report this in a separate issue, but I am following up "the case of the missing docs". I seem to be able to reproduce the behaviour, and it has nothing to do with the Level 3 CDN (for which GH have refreshed their caches), but rather the Backbone SPA the page is made up from. What got me on track was trying to browse the page on my mobile, and actually seeing the `ignore_certificate_errors` on the 0.21.3 page.

I still could not see it when *going to the link directly*, so two different ways of accessing the same url gave different results. Examining the network traffic and noticing that a small json file was sent over the wire: `v0.21.3.json`, I looked at that file, and lo and behold: it did contain the `ignore_certificate_errors` property. So why doesn't the page show it to me?

From the network traffic (I haven't looked at the JS), I am *guessing* this is what's happening:
- The SPA is first loading the default page (using the `HEAD.json` to fill the content)
- Then when the page has loaded it fills the "Version : v0.21.3" field, but does not update the main content with the values from `v0.21.3.json`.

Maybe I'm a bit off on the loading and logic, but at least I can reproduce this consistently, and I don't have to resort to magic explanations about the CDN :-)

**Comment by ethomson** [comment] 2015-02-05 14:13
That's...  very odd.  I also can't reproduce this behavior.  With your explanation about dynamically swapping in different JSON, I must ask if there's some chance that you're using a development version of a browser?  (Or something very standards compliant, where things like Chrome and Safari might be more... em, forgiving.)

Some way to point us towards reproducing this would help.  Thanks!

**Comment by fatso83** [comment] 2015-02-05 17:04
So ... you are saying, that if you go to https://libgit2.github.com/libgit2/#v0.21.3/type/git_clone_options you see `ignore_certificate_errors` somewhere on that page?

I have tried with Chrome (40.0.2214.94) in both normal and incognito mode, Firefox and Safari. They all show this consistent behaviour:
1. Go to https://libgit2.github.com/libgit2/#v0.21.3/type/git_clone_options. There will be no `ignore_certificate_errors` string on that page.
2. Press the `attr` link in the right and let the new page load
3. Then in the right hand side, click 'Types', find `git_clone_options` and press the link.
4. Observe that the url now shows `https://libgit2.github.com/libgit2/#v0.21.3/type/git_clone_options` as before, but the number of fields showing is vastly less and now the `ignore_certificate_errors` is present.

Here are screenshots from Firefox 18 (old) showing the same as in the newest Chrome
![Firefox, 1](https://cloud.githubusercontent.com/assets/618076/6064828/fb00f1be-ad60-11e4-9f00-06f01fdc6753.png)
![Firefox, 2](https://cloud.githubusercontent.com/assets/618076/6064830/fe75d602-ad60-11e4-9459-9cabecb17d06.png)

**Comment by ethomson** [comment] 2015-02-05 17:08
Ugh.  I thought so?  But now I definitely see what you're talking about.

Thanks for reporting this.

@carlosmn does this make any sense to you?

**Comment by carlosmn** [comment] 2015-02-06 00:35
The app always loads `HEAD.json` initially and then looks at what the current version is and loads whatever that is (which it shouldn't, but that's probably another issue). It looks like the documentation is getting rendered before we notice that we have to load a different version.

**Comment by carlosmn** [comment] 2015-03-17 03:58
I looked at the code a bit more, and I'm now certain that it's the asynchrony between loading the new version of the code and the rendering of the page. The code in the router assumes that `Docurium.setVersion()` will have loaded the new version by the time it returns, but that simply doesn't happen, as the request is done in the background and will run after everything else.

**Comment by carlosmn** [comment] 2015-03-18 19:22
The bug has been fixed in docurium, `gh-pages` has been updated and the fix has been pushed to rubygems.

**Closed by carlosmn** 2015-03-18 19:22 UTC
