### ISSUE TITLE
Rebasing a branch onto another with a different submodule pointer fails

### ISSUE THREAD

**Issue by dkoontz** [libgit2/libgit2#3774] opened 2016-05-06 21:45 UTC
If you rebase a branch onto one that has a different pointer for the same submodule, the rebase fails due to workdir changes being detected. I believe this happens during the call to git_rebase_commit. This operation goes through ok on git core.

**Comment by ethomson** [comment] 2016-05-06 21:47
Thanks for reporting this.  The root cause of this problem is #3608 and will be fixed in #3583.

**Comment by dkoontz** [comment] 2016-05-06 21:54
That's great, I see the other issue is ready to be merged in, when might that be happening?

**Comment by hackhaslam** [comment] 2016-05-12 15:47
It's unfortunately not fixed by #3583. I'll see if I can figure out why.

**Comment by hackhaslam** [comment] 2016-05-12 19:33
@ethomson I just pushed an additional commit to #3583 to fix this. I'll comment on the actual change in the PR.

**Comment by ethomson** [comment] 2016-05-26 06:39
Fixed via #3583.

Thanks for reporting this, and thanks to @hackhaslam for fixing it!

**Closed by ethomson** 2016-05-26 06:39 UTC
