### ISSUE TITLE
diff_file_content_load_workdir_file does not respect gitattributes exclusions

### ISSUE THREAD

**Issue by GsxCasper** [libgit2/libgit2#5655] opened 2020-10-07 01:12 UTC
### Reproduction steps
1) create a new git repo
2) create a folder `data`
3) create a text file `foo.metal` inside the `data` folder with whatever content (it's not relevant)
4) add the file to git and commit. The git status should be clean now and you should have the commit in the log
5) initialize git lfs in the repo by running `git lfs install`
6) create a .gitattribute file in the root folder of the repo with the following content:
```
data/** filter=lfs diff=lfs merge=lfs -text
data/**.metal -filter -diff -merge text
```
(this is supposed to send all files in the data folder through git-lfs with the exception of .metal files, which should be treated as normal text).
7) make a local edit to `data/foo.metal`
8) create a `git_diff` (for example with `git_diff_index_to_workdir`)
9) call `git_patch_from_diff`

### Expected behavior
The generated patch should not go through the lfs filter

### Actual behavior
The generated patch is filtered by lfs.

From a little debugging it looks like `git_attr_get_many_with_session` bails out when it decides that the first rule succeeds without checking that the following rule would unset the filter. I've literally just looked at the code for 30 min so I don't the architecture or what should happen where but at this callstack:

```
git_attr_get_many_with_session(values=<no value available>, repo=0x0000614000046e40, attr_session=0x0000000000000000, flags=0, pathname="data/foo.metal", num_attr=1, names="\xfffffff1\x17") at attr.c:151:6
filter_list_check_attributes(out=<no value available>, repo=0x0000614000046e40, attr_session=0x0000000000000000, fdef=0x000060600004d6c0, src=0x00007ffeefbf9c40) at filter.c:436:10
git_filter_list__load_ext(filters=0x00007ffeefbfa0e0, repo=0x0000614000046e40, blob=0x0000000000000000, path="data/foo.metal", mode=GIT_FILTER_TO_ODB, filter_opts=0x00007ffeefbf9fc0) at filter.c:522:12
git_filter_list_load(filters=0x00007ffeefbfa0e0, repo=0x0000614000046e40, blob=0x0000000000000000, path="data/foo.metal", mode=GIT_FILTER_TO_ODB, flags=1) at filter.c:586:9
diff_file_content_load_workdir_file(fc=0x00006150000e07f0, path=0x00007ffeefbfa340, diff_opts=0x00006150000e0698) at diff_file.c:337:15
diff_file_content_load_workdir(fc=0x00006150000e07f0, diff_opts=0x00006150000e0698) at diff_file.c:396:11
git_diff_file_content__load(fc=0x00006150000e07f0, diff_opts=0x00006150000e0698) at diff_file.c:423:11
patch_generated_load(patch=0x00006150000e0680, output=0x00007ffeefbfa7e0) at patch_generate.c:214:15
patch_generated_create(patch=0x00006150000e0680, output=0x00007ffeefbfa7e0) at patch_generate.c:377:12
git_patch_generated_from_diff(patch_ptr=0x00007ffeefbfaa00, diff=0x0000612000216dc0, idx=0) at patch_generate.c:734:11
git_patch_from_diff(out=0x00007ffeefbfaa00, diff=0x0000612000216dc0, idx=0) at patch.c:210:9
```

I see that in this loop 
```
	git_vector_foreach(&files, i, file) {

		git_attr_file__foreach_matching_rule(file, &path, j, rule) {
```

the file has both rules from the .gitattributes. Also the `num_attr` input parameter has value 1 (not sure if that's correct or not). When the first rule gets evaluated it passes and this code is executed:
```
					if (++num_found == num_attr)
						goto cleanup;
```

causing the second rule to never be evaluated.

### Version of libgit2 (release number or SHA1)
Unsure about the exact hash. I found this issue in GitUp (https://github.com/git-up/GitUp), which was marked as a but in libgit2 (https://github.com/git-up/GitUp/issues/439). The fork they use is (https://github.com/git-up/libgit2/tree/gitup)

### Operating system(s) tested
This was tested on macos 10.15

**Comment by ethomson** [comment] 2020-10-07 09:47
Indeed - we should be evaluating all the attributes to find the _last_ one that matches, not short-circuiting when we find the first.  From the `gitattributes` documentation:

> When more than one pattern matches the path, a later line overrides an earlier line. This overriding is done per attribute.

**Comment by rbmclean** [comment] 2020-12-07 02:02
I'll tackle this as well.

**Comment by rbmclean** [comment] 2020-12-09 14:54
I am unable to replicate this. I've done a fair amount of testing with `git_attr_get_many_with_session` and it seems to work correctly. I believe the issue is using `-filter -merge -diff` instead of `!filter !merge !diff`. As mentioned in a link in the GitUp issue, these have different behaviors. I believe this is a user issue, not a libgit2 issue.

**Comment by ethomson** [comment] 2020-12-09 16:37
@GsxCasper can you provide some more details on reproduction steps?  If not, I'll close this.

**Comment by ethomson** [comment] 2020-12-09 16:37
Thanks @rbmclean for digging in here!

**Comment by GsxCasper** [comment] 2020-12-10 02:26
Sure thing. I'll get you a repro at the beginning of next week as I currently don't have access to my computer until the end of the week.

**Comment by GsxCasper** [comment] 2020-12-16 00:27
@rbmclean thanks for looking into this. I can confirm that with `!filter !merge !diff` instead of `-filter -merge -diff` it seems to work correctly.
I don't know enough about the subtleties of `.gitattributes` but it's expected that `-filter -merge -diff` shouldn't work in this case then we can close this issue as "user error" :)

**Comment by ethomson** [comment] 2024-03-09 11:59
Closing as stale

**Closed by ethomson** 2024-03-09 11:59 UTC
Labels: feedback provided
