### ISSUE TITLE
libgit2.pc still requires openssl even after building with mbedtls

### ISSUE THREAD

**Issue by pravi** [libgit2/libgit2#4651] opened 2018-05-21 17:29 UTC
### Reproduction steps

Build libgit2 with mbedtls using the patch from #4173 
Used this patch at https://anonscm.debian.org/git/collab-maint/libgit2.git/tree/debian/patches/use-mbedtls.patch

and build it in a clean chroot without openssl.

### Expected behavior
It should not add openssl as a dependency in .pc.

### Actual behavior

The generated ibgit2.pc has openssl

```
prefix="/usr"
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: libgit2
Description: The git library, take 2
Version: 0.27.0

Libs: -L${libdir} -lgit2
Libs.private: -lrt -lpthread -lhttp_parser -lssh2
Requires.private: openssl zlib

Cflags: -I${includedir}
```
and makes build of other software using libgit2 to fail. See 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899036

### Version of libgit2 (release number or SHA1)

0.27.0

### Operating system(s) tested

Debian unstable/experimental.

**Comment by pravi** [comment] 2018-05-21 17:35
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
-- Found mbedTLS:
--   version 2.8.0
--   TLS: /usr/lib/s390x-linux-gnu/libmbedtls.so
--   X509: /usr/lib/s390x-linux-gnu/libmbedx509.so
--   Crypto: /usr/lib/s390x-linux-gnu/libmbedcrypto.so
Auto-detecting default certificates location
```
Full build log here https://buildd.debian.org/status/fetch.php?pkg=libgit2&arch=s390x&ver=0.27.0%2Bdfsg.1-0.1&stamp=1526122841&raw=0

**Comment by tiennou** [comment] 2018-05-22 20:34
Looking at the build log, I have the following questions:

- you're not using the correct CMake variable for backend selection (IOW `-DUSE_OPENSSL=NO` does nothing, and you're relying on the backend autodetection (hence the lines you're getting). Use `-DUSE_HTTPS=mbedTLS` instead so the autodetection doesn't kick in.
- What backend is libssh2 linking against ? Right now libssh2 is the only "way" to get [unexpected dependencies](https://github.com/libgit2/libgit2/blob/master/src/CMakeLists.txt#L345) in the pkgconfig file, so maybe it's a transient dependency issue ?

I'll be doing some checks locally though, because I don't see what can cause that openssl string to appear in the .pc file at all…

**Comment by tiennou** [comment] 2018-05-22 21:47
Ok, local check done  ([build log](https://gist.github.com/tiennou/4ad49e60b2928260972dba5f0d9d109d)). I've been testing on an Ubuntu 14.04 VM against a source install of mbedTLS 2.9 and manually removing OpenSSL so the autodetect would take place but use mbedTLS. I got this pc file out of `cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DUSE_OPENSSL:BOOL=OFF -DUSE_CURL_SSL:BOOL=ON -DUSE_GSSAPI:BOOL=ON -DTHREADSAFE:BOOL=ON -DBUILD_CLAR:BOOL=ON -DLIB_INSTALL_DIR:STRING=lib/s390x-linux-gnu`
```
prefix="/usr/local"
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libgit2
Description: The git library, take 2
Version: 0.27.0

Libs: -L${libdir} -lgit2
Libs.private: -lrt -lpthread -lcurl -Wl,-Bsymbolic-functions -Wl,-z,relro -lssh2 -lgcrypt
Requires.private: mbedtls zlib

Cflags: -I${includedir}
```

Unrelated, but IIRC 0.27 shipped with #4173, so the external patch should not be needed.

**Comment by pravi** [comment] 2018-05-24 12:15
@tiennou thanks, adding -DUSE_HTTPS=mbedTLS removes the openssl dependency. It would be more logical to have it even when mbedTLS was autodetected instead of setting this variable. But since I got a solution for my problem right now, this issue could be closed if its a lot of work.

**Comment by tiennou** [comment] 2018-05-24 12:32
Glad to hear that you can workaround it. I'll keep the issue around, because I don't understand what caused the autodetection (assuming it's even its fault) to select OpenSSL while it's not detected…

Ok, I'm even more confused, OpenSSL looks to be available (`openssl_1.1.0h-2`, per "Package versions:" in the "Build environment" block), and make processes `streams/openssl.c.o` even though CMake says that it couldn't detect it…

Hence, I'll keep the issue open and try to reproduce against debian-unstable. Thanks for the heads-up!

**Comment by pravi** [comment] 2018-05-24 12:39
openssl header files are missing because libssl-dev is not installed. So cmake can't find the headers (only shared lib is installed probably for another dependency).

**Comment by pravi** [comment] 2018-05-24 14:34
Now there is another problem, mbedtls-dev package does not ship a .pc file.

**Comment by tiennou** [comment] 2018-05-24 14:55
Yep (https://github.com/ARMmbed/mbedtls/issues/228), but normally we have a CMake module that takes care of manually checking for its availability (the `-- Found mbedTLS:` lines).

Thanks for the pointer on the OpenSSL shared lib though, that's helpful (though I still can't understand why it's causing the half-detection you're experiencing).

**Comment by pravi** [comment] 2018-05-24 16:55
Should I open a new issue to track missing pkg-config support in mbedTLS? This means libgit2.pc should not add mbedTLS as a dependency because it will not work until mbedTLS supports pkg-config.

Many packages now fail to build, this example from geany-plugins package. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899036

```
Package mbedtls was not found in the pkg-config search path.
Perhaps you should add the directory containing `mbedtls.pc'
to the PKG_CONFIG_PATH environment variable
Package 'mbedtls', required by 'libgit2', not found
```

**Comment by tiennou** [comment] 2018-05-24 20:17
Well, I can see 2 solutions : don't say anything about mbedTLS in our pkgconfig file, or fix ARMmbed/mbedtls#228. I suspect the former doesn't really fix the issue because downstream would have to somehow provide link flags for mbedtls ?

Sorry, I have no packaging experience, I wasn't aware that pkgconfig dependencies were mandatory… I'll try to see how easy it is to build a .pc file for mbedTLS.

**Comment by pravi** [comment] 2018-05-25 08:37
James Cowgill suggested the following at 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900015#20

 libgit2 should not have a "Requires.private: mbedtls" directive which will obviously not work. Use Libs.private instead until this bug is fixed.

**Comment by tiennou** [comment] 2018-05-25 09:32
Sounds fair, here's a PR implementing that. @pravi can you test that it fixes the pkgconfig issue ?

**Comment by pravi** [comment] 2018-05-26 11:53
@tiennou thanks, I can build geany-plugins now with this patch. I have done half part of mbedtls.pc here https://github.com/ARMmbed/mbedtls/pull/1657 (now need to add bits to install the generated file to correct place)

**Comment by pks-t** [comment] 2018-06-01 11:11
Seems like your issue is resolved now, right? Can we close this ticket, then?

**Comment by pravi** [comment] 2018-06-01 11:38
@pks-t yes, from my side I have no issues. @tiennou do you still want to work on the auto detection issue?

**Comment by tiennou** [comment] 2018-06-01 12:07
To be frank, I don't have any rational explanation about what could have caused the auto-detection failure in the first place… So @pravi's issue is fixed, yes, but the auto-detect did fail in an unexpected way, and I haven't been able to reproduce it locally. I suspect something strange happened because of the chroot used by the build + a combination of "unknown" build flags passed…

Relevant excerpt from the original build log :

```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
-- Found mbedTLS:
--   version 2.8.0
[snip]
Auto-detecting default certificates location
[snip]
-- Enabled features:
 * threadsafe, threadsafe support
 * CERT_LOCATION, using certificates from /usr/lib/ssl/certs/ca-certificates.crt
 * HTTPS, using mbedTLS
```

This means the auto-detect correctly skipped OpenSSL, chose mbedTLS, so the mbedTLS certificate locator runs, but the final libgit2.pc file ends up referring to OpenSSL anyway 😕.

I'm 👍 for closing, since manually specifying the backend (should always) work.

**Comment by tiennou** [comment] 2018-06-01 12:10
Also @pravi, in case that helps, I've put my provisional mbedtls pkgconfig setup in a [feature/add-pc-file](https://github.com/tiennou/mbedtls/tree/feature/add-pc-file).

**Comment by pks-t** [comment] 2018-06-01 12:19
Okay, I'm closing this issue. I guess having a new issue for the autodetect would be less confusing anyway. Thanks to you both!

**Closed by pks-t** 2018-06-01 12:19 UTC

**Comment by pravi** [comment] 2018-06-02 05:45
@tiennou I have done some initial work here https://github.com//ARMmbed/mbedtls/pull/1657 but I'm very very new to this stuff and coding is not really my forte, so if you can take over the pull request, that would be awesome!
