### ISSUE TITLE
Fetch fails with passphrase-protected keypair, but not passphraseless

### ISSUE THREAD

**Issue by terminalmage** [libgit2/libgit2#4221] opened 2017-04-28 05:03 UTC
Note that I am using libgit2 via pygit2, but this does not seem to be pygit2-related, for reasons I will explain.

### Reproduction steps
 
1. Create 2 RSA keypairs, one with a passphrase and one without.

2. On Ubuntu 16.04 LTS, install the ``python-pygit2`` package. This will (as of today, 27 April 2017) pull in pygit2 0.24.0 and libgit2 0.24.1.

3. Attempt to fetch using both a passphraseless and a passphrase-protected key:

```python
>>> repo = pygit2.Repository('.')
>>> origin = repo.remotes[0]
>>> creds_nopass = pygit2.Keypair('gitpillaruser', '/root/.ssh/id_rsa_KonpUlBy.pub'
, '/root/.ssh/id_rsa_KonpUlBy', None)
>>> creds_withpass = pygit2.Keypair('gitpillaruser', '/root/.ssh/id_rsa_WOkArzYX.pu
b', '/root/.ssh/id_rsa_WOkArzYX', 'saltrules')
>>> origin.fetch(callbacks=pygit2.RemoteCallbacks(credentials=creds_nopass))
<pygit2.remote.TransferProgress object at 0x7feb0919ac90>
>>> origin.fetch(callbacks=pygit2.RemoteCallbacks(credentials=creds_withpass))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pygit2/remote.py", line 378, in fetch
    check_error(err)
  File "/usr/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Failed to authenticate SSH session: Callback returned error
>>>
```

### Expected behavior

Both fetches work.

### Actual behavior

The one in which a passphrase-protected key is used fails.

### Version of libgit2 (release number or SHA1)

0.24.1

### Operating system(s) tested

**Ubuntu 16.04 LTS (Does not work)**
- pygit2 0.24.0
- libgit2 0.24.1
- libssh2 1.5.0

**CentOS 7.3 (Works)**
- pygit2 0.24.2
- libgit2 0.26.2
- libssh2 1.4.3

### Additional Comments
 
So, weirdly enough, using an identical setup on CentOS 7 (same exact keys), the fetch works both with a passphraseless and passphrase-protected key.

I dumped some debugging code into pygit2 to find the error code that libgit2 was returning back from it's connection attempt, and found that the code is ``-1``.

Digging further into the pygit2 source code, I found that it is calling out to libgit2's ``git_remote_fetch()`` function from ``remote.c``. When ``git_remote_fetch()`` invokes ``git_remote_connect()``, that function can return ``-1`` if there is no fetch URL defined for the remote, but that is definitely not the case as the passphraseless key works just fine with the same remote. So, I can only assume that the ``-1`` is coming from libssh2 (though I may be wrong about this).

This is where things start to get murky. There is a constant defined as ``-1`` in libssh, but it's also still to this day used as a generic return:

```
/* The library once used -1 as a generic error return value on numerous places
   through the code, which subsequently was converted to
   LIBSSH2_ERROR_SOCKET_NONE uses over time. As this is a generic error code,
   the goal is to never ever return this code but instead make sure that a
   more accurate and descriptive error code is used. */
#define LIBSSH2_ERROR_SOCKET_NONE               -1
```

Despite this comment, ``-1`` is still used in a number of places, and this is where my understanding of the low-level workings of libgit2/libssh2 breaks down.

To be honest, I'm dubious that this is actually a libgit2 issue, since as noted above, authentication with a passphrase works properly on CentOS 7. Not only that, I used a fresh Ubuntu 16.04 box and compiled and installed libgit2 0.24.6 and then installed pygit2 0.24.2 to try to match CentOS 7 as closely as possible (I did not try downgrading libssh2 to 1.4.3). The behavior remained unchanged on Ubuntu 16.04, the passphrase authentication still failed. So, it seems less and less likely that this is actually a libgit2 bug, but I've reached the edge of where my troubleshooting skills extend, and I could use some insight. Any information you could provide would be greatly appreciated.

**Comment by eliasp** [comment] 2017-05-01 23:15
I can reproduce exactly the same issue here on Debian 9/stretch using:
- Python: `2.7.13`
- pygit2: `0.24.2`
- libgit2: `0.24.5`
- libssh2: `1.7.0`

Ran into this while migrating existing/working keys from a CentOS7 box to a Debian 9 box.

**Comment by ethomson** [comment] 2024-02-22 22:59
Apologies that we didn't make more progress here - I hope that your problem is resolved. I'm going to close this since this issue is quite old and has not had further comments. LMK if this remains an issue.

**Closed by ethomson** 2024-02-22 22:59 UTC
