### ISSUE TITLE
Checkout implementation does not correctly detect modified files in workdir

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2703] opened 2014-11-13 13:32 UTC
This nasty bug took me some time to track down but at least one effect of it is that `git_checkout_tree()` is not working correctly on OS X in some cases: some files are not updated while they should. There might be some other side-effects.

The HFS+ file system, which is the default on OS X, does not support sub-second resolution for modification time. This means that if a file has been modified in the workdir within the same second after it's been staged *AND* its content length has not changed either, this piece of code in `checkout_is_workdir_modified()` will pass:
```c
	/* Look at the cache to decide if the workdir is modified.  If not,
	 * we can simply compare the oid in the cache to the baseitem instead
	 * of hashing the file.  If so, we allow the checkout to proceed if the
	 * oid is identical (ie, the staged item is what we're trying to check
	 * out.)
	 */
	if ((ie = git_index_get_bypath(data->index, wditem->path, 0)) != NULL) {
		if (wditem->mtime.seconds == ie->mtime.seconds &&
			wditem->mtime.nanoseconds == ie->mtime.nanoseconds &&
			wditem->file_size == ie->file_size)
			return (git_oid__cmp(&baseitem->id, &ie->id) != 0 &&
				git_oid_cmp(&newitem->id, &ie->id) != 0);
	}
```

In general I don't think this piece of code is safe anyway and it should be removed entirely. It only makes sense on file systems which implement true nanosecond modification time resolution as it's pretty much impossible (I assume?) that a file can be modified within the same nanosecond. And then the file size comparison is redundant anyway (and as demonstrated here, it's not even correcting false positives).

A simple way to reproduce is to programmatically:
- Create a commit with a new file containing the string "1"
- Change this file to contain the string "2" (this must be done within the same second as the previous step obviously)
- Call `git_checkout_tree()` passing the tree of the commit and the FORCE option
- The file content is still "2" instead of "1"

**Comment by carlosmn** [comment] 2015-06-26 12:10
Is any of this still relevant now that racy-git has been implemented?

**Comment by swisspol** [comment] 2015-06-26 15:32
Yes, this issue is still happening - a simple functional test based on the steps in the description of this issue demonstrates it:
```objc
- (void)testTemp {
  GCCommit* commit = [self makeCommitWithUpdatedFileAtPath:@"hello_world.txt" string:@"1" message:@"1"];
  [self updateFileAtPath:@"hello_world.txt" withString:@"2"];
  XCTAssertTrue([self.repository checkoutCommit:commit options:kGCCheckoutOption_Force error:NULL]);
  [self assertContentsOfFileAtPath:@"hello_world.txt" equalsString:@"1"];   <---- FAIL
}
```

Adding a `sleep()` call works around the issue as expected:
```objc
- (void)testTemp {
  GCCommit* commit = [self makeCommitWithUpdatedFileAtPath:@"hello_world.txt" string:@"1" message:@"1"];
  
  sleep(1);
  
  [self updateFileAtPath:@"hello_world.txt" withString:@"2"];
  XCTAssertTrue([self.repository checkoutCommit:commit options:kGCCheckoutOption_Force error:NULL]);
  [self assertContentsOfFileAtPath:@"hello_world.txt" equalsString:@"1"];  <---- PASS
}
```

**Comment by GrahamTheCoder** [comment] 2016-01-29 13:59
We're currently hitting this issue when trying to stage files changed (programatically) shortly after a commit. I think nanos is always 0 so even though we explicitly listed the paths to stage libgit2 decides it knows better. Currently searching for a workaround that doesn't needs a 1s sleep.

**Comment by ethomson** [comment] 2016-01-29 14:27
@GrahamTheCoder I can't reproduce this trivially, can you post some code?  What version of libgit2?

**Comment by tomcsmith1990** [comment] 2016-01-29 15:51
@ethomson here's a repro using libgit2sharp 0.21.0.176:

```
        [Test]
        public void IdenticalLengthFileChangedSoonAfterCommitShouldBeAChange()
        {
            var directory = Directory.CreateDirectory($@"C:\Temp\libgit2sharp\{Guid.NewGuid()}");
            Repository.Init(directory.FullName);
            using (var repo = new Repository(directory.FullName))
            {
                var signature = new Signature("name", "email", DateTimeOffset.UtcNow);

                var filename = Path.Combine(directory.FullName, "foo.txt");
                File.WriteAllText(filename, "test1");
                repo.Stage(filename);
                repo.Commit("message", signature, signature);

                File.WriteAllText(filename, "test2");

                repo.Stage(filename);
                Assert.That(
                    repo.RetrieveStatus(filename) & FileStatus.Modified,
                    Is.True,
                    $"{filename} should be modified");
            }
```

`Repository.Stage` uses `Repository.Diff.Compare<TreeChanges>`, which has the same problem - it sees no changes.

This also occurs on the latest pre-release package `0.22.0-pre20151023210959`.

**Comment by ethomson** [comment] 2016-02-09 22:22
@tomcsmith1990 Firstly, I think that you will need to use LibGit2Sharp 0.22 prerelease, I do not think that 0.21 has the racy fixes.

Second, your test is not correct - `RetrieveStatus` should be returning `Staged` in the success case, not `Modified`.  (If you remove the `Stage` line above your test, then it should in fact be returning `Modified`).

Can you try again with 0.22.0 prerelease and report back what `RetrieveStatus` is in fact reporting?  I'm seeing this behave correctly.

**Comment by tomcsmith1990** [comment] 2016-02-10 10:33
@ethomson thanks. My assertion was also wrong, since I asserted that status should be `true`, not `FileStatus.Staged`.

After changing the test to use `Staged` and fixing the assertion it does behave correctly using 0.22 prerelease (and fails on 0.21).

**Comment by ethomson** [comment] 2016-02-29 03:43
@swisspol I've spent a lot of time trying to reproduce this since racy-git was introduced, and certainly I cannot.  Are you certain that this is still occurring with a recent libgit2 build?

**Comment by ethomson** [comment] 2016-03-17 21:14
Closing this now that 0.24 is out and all the bindings have been updated to include the racy Git fixes.

**Closed by ethomson** 2016-03-17 21:14 UTC
